// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::command_type::Command;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerCommandArgs {
    pub cmd: Command,
}

impl From<PlayerCommandArgs> for super::Reducer {
    fn from(args: PlayerCommandArgs) -> Self {
        Self::PlayerCommand { cmd: args.cmd }
    }
}

impl __sdk::InModule for PlayerCommandArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerCommandCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_command {
    /// Request that the remote module invoke the reducer `player_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_command`] callbacks.
    fn player_command(&self, cmd: Command) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_command`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerCommandCallbackId`] can be passed to [`Self::remove_on_player_command`]
    /// to cancel the callback.
    fn on_player_command(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Command) + Send + 'static,
    ) -> PlayerCommandCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_command`],
    /// causing it not to run in the future.
    fn remove_on_player_command(&self, callback: PlayerCommandCallbackId);
}

impl player_command for super::RemoteReducers {
    fn player_command(&self, cmd: Command) -> __sdk::Result<()> {
        self.imp
            .call_reducer("player_command", PlayerCommandArgs { cmd })
    }
    fn on_player_command(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Command) + Send + 'static,
    ) -> PlayerCommandCallbackId {
        PlayerCommandCallbackId(self.imp.on_reducer(
            "player_command",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerCommand { cmd },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, cmd)
            }),
        ))
    }
    fn remove_on_player_command(&self, callback: PlayerCommandCallbackId) {
        self.imp.remove_on_reducer("player_command", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_command`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_command {
    /// Set the call-reducer flags for the reducer `player_command` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_command(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_command for super::SetReducerFlags {
    fn player_command(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_command", flags);
    }
}
