const c = @import("vulkan");

cmd: c.VkCommandBuffer,
image: c.VkImage,
layout: Layout = .undefined,
stage: Stage,
access: Access = .none,

pub const Layout = enum(c.VkImageLayout) {
    undefined = c.VK_IMAGE_LAYOUT_UNDEFINED,
    general = c.VK_IMAGE_LAYOUT_GENERAL,
    color_attachment_optimal = c.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
    depth_stencil_attachment_optimal = c.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
    depth_stencil_read_only_optimal = c.VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
    shader_read_only_optimal = c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
    transfer_src_optimal = c.VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
    transfer_dst_optimal = c.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    preinitialized = c.VK_IMAGE_LAYOUT_PREINITIALIZED,
    depth_read_only_stencil_attachment_optimal = c.VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
    depth_attachment_stencil_read_only_optimal = c.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
    depth_attachment_optimal = c.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
    depth_read_only_optimal = c.VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
    stencil_attachment_optimal = c.VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
    stencil_read_only_optimal = c.VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
    read_only_optimal = c.VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
    attachment_optimal = c.VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
    present_src_khr = c.VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
    video_decode_dst_khr = c.VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR,
    video_decode_src_khr = c.VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR,
    video_decode_dpb_khr = c.VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR,
    shared_present_khr = c.VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR,
    fragment_density_map_optimal_ext = c.VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT,
    fragment_shading_rate_attachment_optimal_khr = c.VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
    rendering_local_read_khr = c.VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR,
    video_encode_dst_khr = c.VK_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR,
    video_encode_src_khr = c.VK_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR,
    video_encode_dpb_khr = c.VK_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR,
    attachment_feedback_loop_optimal_ext = c.VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT,
    _,
};

pub const Stage = enum(c.VkPipelineStageFlags) {
    top_of_pipe_bit = c.VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
    draw_indirect_bit = c.VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT,
    vertex_input_bit = c.VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,
    vertex_shader_bit = c.VK_PIPELINE_STAGE_VERTEX_SHADER_BIT,
    tessellation_control_shader_bit = c.VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT,
    tessellation_evaluation_shader_bit = c.VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT,
    geometry_shader_bit = c.VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT,
    fragment_shader_bit = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
    early_fragment_tests_bit = c.VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
    late_fragment_tests_bit = c.VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
    color_attachment_output_bit = c.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
    compute_shader_bit = c.VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
    transfer_bit = c.VK_PIPELINE_STAGE_TRANSFER_BIT,
    bottom_of_pipe_bit = c.VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,
    host_bit = c.VK_PIPELINE_STAGE_HOST_BIT,
    all_graphics_bit = c.VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT,
    all_commands_bit = c.VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
    none = c.VK_PIPELINE_STAGE_NONE,
    transform_feedback_bit_ext = c.VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT,
    conditional_rendering_bit_ext = c.VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT,
    acceleration_structure_build_bit_khr = c.VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
    ray_tracing_shader_bit_khr = c.VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR,
    fragment_density_process_bit_ext = c.VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT,
    fragment_shading_rate_attachment_bit_khr = c.VK_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,
    command_preprocess_bit_nv = c.VK_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV,
    task_shader_bit_ext = c.VK_PIPELINE_STAGE_TASK_SHADER_BIT_EXT,
    mesh_shader_bit_ext = c.VK_PIPELINE_STAGE_MESH_SHADER_BIT_EXT,
    flag_bits_max_enum = c.VK_PIPELINE_STAGE_FLAG_BITS_MAX_ENUM,
    _,
};

pub const Access = enum(c.VkAccessFlags) {
    indirect_command_read_bit = c.VK_ACCESS_INDIRECT_COMMAND_READ_BIT,
    index_read_bit = c.VK_ACCESS_INDEX_READ_BIT,
    vertex_attribute_read_bit = c.VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT,
    uniform_read_bit = c.VK_ACCESS_UNIFORM_READ_BIT,
    input_attachment_read_bit = c.VK_ACCESS_INPUT_ATTACHMENT_READ_BIT,
    shader_read_bit = c.VK_ACCESS_SHADER_READ_BIT,
    shader_write_bit = c.VK_ACCESS_SHADER_WRITE_BIT,
    color_attachment_read_bit = c.VK_ACCESS_COLOR_ATTACHMENT_READ_BIT,
    color_attachment_write_bit = c.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
    depth_stencil_attachment_read_bit = c.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT,
    depth_stencil_attachment_write_bit = c.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
    transfer_read_bit = c.VK_ACCESS_TRANSFER_READ_BIT,
    transfer_write_bit = c.VK_ACCESS_TRANSFER_WRITE_BIT,
    host_read_bit = c.VK_ACCESS_HOST_READ_BIT,
    host_write_bit = c.VK_ACCESS_HOST_WRITE_BIT,
    memory_read_bit = c.VK_ACCESS_MEMORY_READ_BIT,
    memory_write_bit = c.VK_ACCESS_MEMORY_WRITE_BIT,
    none = c.VK_ACCESS_NONE,
    transform_feedback_write_bit_ext = c.VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT,
    transform_feedback_counter_read_bit_ext = c.VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT,
    transform_feedback_counter_write_bit_ext = c.VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT,
    conditional_rendering_read_bit_ext = c.VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT,
    color_attachment_read_noncoherent_bit_ext = c.VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT,
    acceleration_structure_read_bit_khr = c.VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR,
    acceleration_structure_write_bit_khr = c.VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR,
    fragment_density_map_read_bit_ext = c.VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT,
    fragment_shading_rate_attachment_read_bit_khr = c.VK_ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR,
    command_preprocess_read_bit_nv = c.VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV,
    command_preprocess_write_bit_nv = c.VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV,
    _,
};

pub fn init(cmd: c.VkCommandBuffer, image: c.VkImage, stage: ?Stage) @This() {
    return .{
        .cmd = cmd,
        .image = image,
        .stage = stage orelse .top_of_pipe_bit,
    };
}

pub fn transition(self: *@This(), layout: Layout, stage: Stage, access: c.VkAccessFlags) void {
    var new: c.VkImageMemoryBarrier = .{
        .sType = c.VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
        // .srcStageMask = src_stage,
        .srcAccessMask = @intFromEnum(access),
        // .dstStageMask = dst_stage,
        .dstAccessMask = @intFromEnum(self.access),
        .oldLayout = @intFromEnum(self.layout),
        .newLayout = @intFromEnum(layout),
        .srcQueueFamilyIndex = c.VK_QUEUE_FAMILY_IGNORED,
        .dstQueueFamilyIndex = c.VK_QUEUE_FAMILY_IGNORED,
        .image = self.image,
        .subresourceRange = .{
            .aspectMask = c.VK_IMAGE_ASPECT_COLOR_BIT,
            .baseMipLevel = 0,
            .levelCount = 1,
            .baseArrayLayer = 0,
            .layerCount = 1,
        },
    };
    c.vkCmdPipelineBarrier(self.cmd, @intFromEnum(stage), @intFromEnum(self.stage), 0, 0, null, 0, null, 1, &new);
    self.*.layout = layout;
    self.*.stage = stage;
    self.*.access = access;
}
