const std = @import("std");
const c = @import("vulkan");

pub fn check(result: c.VkResult) !void {
    if (result != c.VK_SUCCESS) return switch (result) {
        c.VK_ERROR_OUT_OF_HOST_MEMORY => error.OutOfHostMemory,
        c.VK_ERROR_OUT_OF_DEVICE_MEMORY => error.OutOfDeviceMemory,
        c.VK_ERROR_INITIALIZATION_FAILED => error.InitializationFailed,
        c.VK_ERROR_DEVICE_LOST => error.DeviceLost,
        c.VK_ERROR_MEMORY_MAP_FAILED => error.MemoryMapFailed,
        c.VK_ERROR_LAYER_NOT_PRESENT => error.LayerNotPresent,
        c.VK_ERROR_EXTENSION_NOT_PRESENT => error.ExtensionNotPresent,
        c.VK_ERROR_FEATURE_NOT_PRESENT => error.FeatureNotPresent,
        c.VK_ERROR_INCOMPATIBLE_DRIVER => error.IncompatibleDriver,
        c.VK_ERROR_TOO_MANY_OBJECTS => error.TooManyObjects,
        c.VK_ERROR_FORMAT_NOT_SUPPORTED => error.FormatNotSupported,
        c.VK_ERROR_FRAGMENTED_POOL => error.FragmentedPool,
        c.VK_ERROR_OUT_OF_POOL_MEMORY => error.OutOfPoolMemory,
        c.VK_ERROR_INVALID_EXTERNAL_HANDLE => error.InvalidExternalHandle,
        c.VK_ERROR_FRAGMENTATION => error.Fragmentation,
        c.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS => error.InvalidOpaqueCaptureAddress,
        c.VK_PIPELINE_COMPILE_REQUIRED => error.PipelineCompileRequired,
        c.VK_ERROR_SURFACE_LOST_KHR => error.SurfaceLostKhr,
        c.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR => error.NativeWindowInUseKhr,
        c.VK_SUBOPTIMAL_KHR => error.SuboptimalKhr,
        c.VK_ERROR_OUT_OF_DATE_KHR => error.OutOfDateKhr,
        c.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR => error.IncompatibleDisplayKhr,
        c.VK_ERROR_VALIDATION_FAILED_EXT => error.ValidationFailedExt,
        c.VK_ERROR_INVALID_SHADER_NV => error.InvalidShaderNv,
        c.VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR => error.ImageUsageNotSupportedKhr,
        c.VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR => error.VideoPictureLayoutNotSupportedKhr,
        c.VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR => error.VideoProfileOperationNotSupportedKhr,
        c.VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR => error.VideoProfileFormatNotSupportedKhr,
        c.VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR => error.VideoProfileCodecNotSupportedKhr,
        c.VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR => error.VideoStdVersionNotSupportedKhr,
        c.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT => error.InvalidDrmFormatModifierPlaneLayoutExt,
        c.VK_ERROR_NOT_PERMITTED_KHR => error.NotPermittedKhr,
        c.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT => error.FullScreenExclusiveModeLostExt,
        c.VK_THREAD_IDLE_KHR => error.ThreadIdleKhr,
        c.VK_THREAD_DONE_KHR => error.ThreadDoneKhr,
        c.VK_OPERATION_DEFERRED_KHR => error.OperationDeferredKhr,
        c.VK_OPERATION_NOT_DEFERRED_KHR => error.OperationNotDeferredKhr,
        c.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR => error.InvalidVideoStdParametersKhr,
        c.VK_ERROR_COMPRESSION_EXHAUSTED_EXT => error.CompressionExhaustedExt,
        c.VK_INCOMPATIBLE_SHADER_BINARY_EXT => error.IncompatibleShaderBinaryExt,
        c.VK_ERROR_UNKNOWN => error.Unknown,
        else => error.Unknown,
    };
}

pub const Func = enum {
    allocationFunction,
    reallocationFunction,
    freeFunction,
    internalAllocationNotification,
    internalFreeNotification,
    createInstance,
    destroyInstance,
    enumeratePhysicalDevices,
    getPhysicalDeviceFeatures,
    getPhysicalDeviceFormatProperties,
    getPhysicalDeviceImageFormatProperties,
    getPhysicalDeviceProperties,
    getPhysicalDeviceQueueFamilyProperties,
    getPhysicalDeviceMemoryProperties,
    getInstanceProcAddr,
    getDeviceProcAddr,
    createDevice,
    destroyDevice,
    enumerateInstanceExtensionProperties,
    enumerateDeviceExtensionProperties,
    enumerateInstanceLayerProperties,
    enumerateDeviceLayerProperties,
    getDeviceQueue,
    queueSubmit,
    queueWaitIdle,
    deviceWaitIdle,
    allocateMemory,
    freeMemory,
    mapMemory,
    unmapMemory,
    flushMappedMemoryRanges,
    invalidateMappedMemoryRanges,
    getDeviceMemoryCommitment,
    bindBufferMemory,
    bindImageMemory,
    getBufferMemoryRequirements,
    getImageMemoryRequirements,
    getImageSparseMemoryRequirements,
    getPhysicalDeviceSparseImageFormatProperties,
    queueBindSparse,
    createFence,
    destroyFence,
    resetFences,
    getFenceStatus,
    waitForFences,
    createSemaphore,
    destroySemaphore,
    createEvent,
    destroyEvent,
    getEventStatus,
    setEvent,
    resetEvent,
    createQueryPool,
    destroyQueryPool,
    getQueryPoolResults,
    createBuffer,
    destroyBuffer,
    createBufferView,
    destroyBufferView,
    createImage,
    destroyImage,
    getImageSubresourceLayout,
    createImageView,
    destroyImageView,
    createShaderModule,
    destroyShaderModule,
    createPipelineCache,
    destroyPipelineCache,
    getPipelineCacheData,
    mergePipelineCaches,
    createGraphicsPipelines,
    createComputePipelines,
    destroyPipeline,
    createPipelineLayout,
    destroyPipelineLayout,
    createSampler,
    destroySampler,
    createDescriptorSetLayout,
    destroyDescriptorSetLayout,
    createDescriptorPool,
    destroyDescriptorPool,
    resetDescriptorPool,
    allocateDescriptorSets,
    freeDescriptorSets,
    updateDescriptorSets,
    createFramebuffer,
    destroyFramebuffer,
    createRenderPass,
    destroyRenderPass,
    getRenderAreaGranularity,
    createCommandPool,
    destroyCommandPool,
    resetCommandPool,
    allocateCommandBuffers,
    freeCommandBuffers,
    beginCommandBuffer,
    endCommandBuffer,
    resetCommandBuffer,
    cmdBindPipeline,
    cmdSetViewport,
    cmdSetScissor,
    cmdSetLineWidth,
    cmdSetDepthBias,
    cmdSetBlendConstants,
    cmdSetDepthBounds,
    cmdSetStencilCompareMask,
    cmdSetStencilWriteMask,
    cmdSetStencilReference,
    cmdBindDescriptorSets,
    cmdBindIndexBuffer,
    cmdBindVertexBuffers,
    cmdDraw,
    cmdDrawIndexed,
    cmdDrawIndirect,
    cmdDrawIndexedIndirect,
    cmdDispatch,
    cmdDispatchIndirect,
    cmdCopyBuffer,
    cmdCopyImage,
    cmdBlitImage,
    cmdCopyBufferToImage,
    cmdCopyImageToBuffer,
    cmdUpdateBuffer,
    cmdFillBuffer,
    cmdClearColorImage,
    cmdClearDepthStencilImage,
    cmdClearAttachments,
    cmdResolveImage,
    cmdSetEvent,
    cmdResetEvent,
    cmdWaitEvents,
    cmdPipelineBarrier,
    cmdBeginQuery,
    cmdEndQuery,
    cmdResetQueryPool,
    cmdWriteTimestamp,
    cmdCopyQueryPoolResults,
    cmdPushConstants,
    cmdBeginRenderPass,
    cmdNextSubpass,
    cmdEndRenderPass,
    cmdExecuteCommands,
    enumerateInstanceVersion,
    bindBufferMemory2,
    bindImageMemory2,
    getDeviceGroupPeerMemoryFeatures,
    cmdSetDeviceMask,
    cmdDispatchBase,
    enumeratePhysicalDeviceGroups,
    getImageMemoryRequirements2,
    getBufferMemoryRequirements2,
    getImageSparseMemoryRequirements2,
    getPhysicalDeviceFeatures2,
    getPhysicalDeviceProperties2,
    getPhysicalDeviceFormatProperties2,
    getPhysicalDeviceImageFormatProperties2,
    getPhysicalDeviceQueueFamilyProperties2,
    getPhysicalDeviceMemoryProperties2,
    getPhysicalDeviceSparseImageFormatProperties2,
    trimCommandPool,
    getDeviceQueue2,
    createSamplerYcbcrConversion,
    destroySamplerYcbcrConversion,
    createDescriptorUpdateTemplate,
    destroyDescriptorUpdateTemplate,
    updateDescriptorSetWithTemplate,
    getPhysicalDeviceExternalBufferProperties,
    getPhysicalDeviceExternalFenceProperties,
    getPhysicalDeviceExternalSemaphoreProperties,
    getDescriptorSetLayoutSupport,
    cmdDrawIndirectCount,
    cmdDrawIndexedIndirectCount,
    createRenderPass2,
    cmdBeginRenderPass2,
    cmdNextSubpass2,
    cmdEndRenderPass2,
    resetQueryPool,
    getSemaphoreCounterValue,
    waitSemaphores,
    signalSemaphore,
    getBufferDeviceAddress,
    getBufferOpaqueCaptureAddress,
    getDeviceMemoryOpaqueCaptureAddress,
    getPhysicalDeviceToolProperties,
    createPrivateDataSlot,
    destroyPrivateDataSlot,
    setPrivateData,
    getPrivateData,
    cmdSetEvent2,
    cmdResetEvent2,
    cmdWaitEvents2,
    cmdPipelineBarrier2,
    cmdWriteTimestamp2,
    queueSubmit2,
    cmdCopyBuffer2,
    cmdCopyImage2,
    cmdCopyBufferToImage2,
    cmdCopyImageToBuffer2,
    cmdBlitImage2,
    cmdResolveImage2,
    cmdBeginRendering,
    cmdEndRendering,
    cmdSetCullMode,
    cmdSetFrontFace,
    cmdSetPrimitiveTopology,
    cmdSetViewportWithCount,
    cmdSetScissorWithCount,
    cmdBindVertexBuffers2,
    cmdSetDepthTestEnable,
    cmdSetDepthWriteEnable,
    cmdSetDepthCompareOp,
    cmdSetDepthBoundsTestEnable,
    cmdSetStencilTestEnable,
    cmdSetStencilOp,
    cmdSetRasterizerDiscardEnable,
    cmdSetDepthBiasEnable,
    cmdSetPrimitiveRestartEnable,
    getDeviceBufferMemoryRequirements,
    getDeviceImageMemoryRequirements,
    getDeviceImageSparseMemoryRequirements,
    destroySurfaceKHR,
    getPhysicalDeviceSurfaceSupportKHR,
    getPhysicalDeviceSurfaceCapabilitiesKHR,
    getPhysicalDeviceSurfaceFormatsKHR,
    getPhysicalDeviceSurfacePresentModesKHR,
    createSwapchainKHR,
    destroySwapchainKHR,
    getSwapchainImagesKHR,
    acquireNextImageKHR,
    queuePresentKHR,
    getDeviceGroupPresentCapabilitiesKHR,
    getDeviceGroupSurfacePresentModesKHR,
    getPhysicalDevicePresentRectanglesKHR,
    acquireNextImage2KHR,
    getPhysicalDeviceDisplayPropertiesKHR,
    getPhysicalDeviceDisplayPlanePropertiesKHR,
    getDisplayPlaneSupportedDisplaysKHR,
    getDisplayModePropertiesKHR,
    createDisplayModeKHR,
    getDisplayPlaneCapabilitiesKHR,
    createDisplayPlaneSurfaceKHR,
    createSharedSwapchainsKHR,
    getPhysicalDeviceVideoCapabilitiesKHR,
    getPhysicalDeviceVideoFormatPropertiesKHR,
    createVideoSessionKHR,
    destroyVideoSessionKHR,
    getVideoSessionMemoryRequirementsKHR,
    bindVideoSessionMemoryKHR,
    createVideoSessionParametersKHR,
    updateVideoSessionParametersKHR,
    destroyVideoSessionParametersKHR,
    cmdBeginVideoCodingKHR,
    cmdEndVideoCodingKHR,
    cmdControlVideoCodingKHR,
    cmdDecodeVideoKHR,
    cmdBeginRenderingKHR,
    cmdEndRenderingKHR,
    getPhysicalDeviceFeatures2KHR,
    getPhysicalDeviceProperties2KHR,
    getPhysicalDeviceFormatProperties2KHR,
    getPhysicalDeviceImageFormatProperties2KHR,
    getPhysicalDeviceQueueFamilyProperties2KHR,
    getPhysicalDeviceMemoryProperties2KHR,
    getPhysicalDeviceSparseImageFormatProperties2KHR,
    getDeviceGroupPeerMemoryFeaturesKHR,
    cmdSetDeviceMaskKHR,
    cmdDispatchBaseKHR,
    trimCommandPoolKHR,
    enumeratePhysicalDeviceGroupsKHR,
    getPhysicalDeviceExternalBufferPropertiesKHR,
    getMemoryFdKHR,
    getMemoryFdPropertiesKHR,
    getPhysicalDeviceExternalSemaphorePropertiesKHR,
    importSemaphoreFdKHR,
    getSemaphoreFdKHR,
    cmdPushDescriptorSetKHR,
    cmdPushDescriptorSetWithTemplateKHR,
    createDescriptorUpdateTemplateKHR,
    destroyDescriptorUpdateTemplateKHR,
    updateDescriptorSetWithTemplateKHR,
    createRenderPass2KHR,
    cmdBeginRenderPass2KHR,
    cmdNextSubpass2KHR,
    cmdEndRenderPass2KHR,
    getSwapchainStatusKHR,
    getPhysicalDeviceExternalFencePropertiesKHR,
    importFenceFdKHR,
    getFenceFdKHR,
    enumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR,
    getPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR,
    acquireProfilingLockKHR,
    releaseProfilingLockKHR,
    getPhysicalDeviceSurfaceCapabilities2KHR,
    getPhysicalDeviceSurfaceFormats2KHR,
    getPhysicalDeviceDisplayProperties2KHR,
    getPhysicalDeviceDisplayPlaneProperties2KHR,
    getDisplayModeProperties2KHR,
    getDisplayPlaneCapabilities2KHR,
    getImageMemoryRequirements2KHR,
    getBufferMemoryRequirements2KHR,
    getImageSparseMemoryRequirements2KHR,
    createSamplerYcbcrConversionKHR,
    destroySamplerYcbcrConversionKHR,
    bindBufferMemory2KHR,
    bindImageMemory2KHR,
    getDescriptorSetLayoutSupportKHR,
    cmdDrawIndirectCountKHR,
    cmdDrawIndexedIndirectCountKHR,
    getSemaphoreCounterValueKHR,
    waitSemaphoresKHR,
    signalSemaphoreKHR,
    getPhysicalDeviceFragmentShadingRatesKHR,
    cmdSetFragmentShadingRateKHR,
    cmdSetRenderingAttachmentLocationsKHR,
    cmdSetRenderingInputAttachmentIndicesKHR,
    waitForPresentKHR,
    getBufferDeviceAddressKHR,
    getBufferOpaqueCaptureAddressKHR,
    getDeviceMemoryOpaqueCaptureAddressKHR,
    createDeferredOperationKHR,
    destroyDeferredOperationKHR,
    getDeferredOperationMaxConcurrencyKHR,
    getDeferredOperationResultKHR,
    deferredOperationJoinKHR,
    getPipelineExecutablePropertiesKHR,
    getPipelineExecutableStatisticsKHR,
    getPipelineExecutableInternalRepresentationsKHR,
    mapMemory2KHR,
    unmapMemory2KHR,
    getPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR,
    getEncodedVideoSessionParametersKHR,
    cmdEncodeVideoKHR,
    cmdSetEvent2KHR,
    cmdResetEvent2KHR,
    cmdWaitEvents2KHR,
    cmdPipelineBarrier2KHR,
    cmdWriteTimestamp2KHR,
    queueSubmit2KHR,
    cmdWriteBufferMarker2AMD,
    getQueueCheckpointData2NV,
    cmdCopyBuffer2KHR,
    cmdCopyImage2KHR,
    cmdCopyBufferToImage2KHR,
    cmdCopyImageToBuffer2KHR,
    cmdBlitImage2KHR,
    cmdResolveImage2KHR,
    cmdTraceRaysIndirect2KHR,
    getDeviceBufferMemoryRequirementsKHR,
    getDeviceImageMemoryRequirementsKHR,
    getDeviceImageSparseMemoryRequirementsKHR,
    cmdBindIndexBuffer2KHR,
    getRenderingAreaGranularityKHR,
    getDeviceImageSubresourceLayoutKHR,
    getImageSubresourceLayout2KHR,
    getPhysicalDeviceCooperativeMatrixPropertiesKHR,
    cmdSetLineStippleKHR,
    getPhysicalDeviceCalibrateableTimeDomainsKHR,
    getCalibratedTimestampsKHR,
    cmdBindDescriptorSets2KHR,
    cmdPushConstants2KHR,
    cmdPushDescriptorSet2KHR,
    cmdPushDescriptorSetWithTemplate2KHR,
    cmdSetDescriptorBufferOffsets2EXT,
    cmdBindDescriptorBufferEmbeddedSamplers2EXT,
    debugReportCallbackEXT,
    createDebugReportCallbackEXT,
    destroyDebugReportCallbackEXT,
    debugReportMessageEXT,
    debugMarkerSetObjectTagEXT,
    debugMarkerSetObjectNameEXT,
    cmdDebugMarkerBeginEXT,
    cmdDebugMarkerEndEXT,
    cmdDebugMarkerInsertEXT,
    cmdBindTransformFeedbackBuffersEXT,
    cmdBeginTransformFeedbackEXT,
    cmdEndTransformFeedbackEXT,
    cmdBeginQueryIndexedEXT,
    cmdEndQueryIndexedEXT,
    cmdDrawIndirectByteCountEXT,
    createCuModuleNVX,
    createCuFunctionNVX,
    destroyCuModuleNVX,
    destroyCuFunctionNVX,
    cmdCuLaunchKernelNVX,
    getImageViewHandleNVX,
    getImageViewAddressNVX,
    cmdDrawIndirectCountAMD,
    cmdDrawIndexedIndirectCountAMD,
    getShaderInfoAMD,
    getPhysicalDeviceExternalImageFormatPropertiesNV,
    cmdBeginConditionalRenderingEXT,
    cmdEndConditionalRenderingEXT,
    cmdSetViewportWScalingNV,
    releaseDisplayEXT,
    getPhysicalDeviceSurfaceCapabilities2EXT,
    displayPowerControlEXT,
    registerDeviceEventEXT,
    registerDisplayEventEXT,
    getSwapchainCounterEXT,
    getRefreshCycleDurationGOOGLE,
    getPastPresentationTimingGOOGLE,
    cmdSetDiscardRectangleEXT,
    cmdSetDiscardRectangleEnableEXT,
    cmdSetDiscardRectangleModeEXT,
    setHdrMetadataEXT,
    debugUtilsMessengerCallbackEXT,
    setDebugUtilsObjectNameEXT,
    setDebugUtilsObjectTagEXT,
    queueBeginDebugUtilsLabelEXT,
    queueEndDebugUtilsLabelEXT,
    queueInsertDebugUtilsLabelEXT,
    cmdBeginDebugUtilsLabelEXT,
    cmdEndDebugUtilsLabelEXT,
    cmdInsertDebugUtilsLabelEXT,
    createDebugUtilsMessengerEXT,
    destroyDebugUtilsMessengerEXT,
    submitDebugUtilsMessageEXT,
    cmdSetSampleLocationsEXT,
    getPhysicalDeviceMultisamplePropertiesEXT,
    getImageDrmFormatModifierPropertiesEXT,
    createValidationCacheEXT,
    destroyValidationCacheEXT,
    mergeValidationCachesEXT,
    getValidationCacheDataEXT,
    cmdBindShadingRateImageNV,
    cmdSetViewportShadingRatePaletteNV,
    cmdSetCoarseSampleOrderNV,
    createAccelerationStructureNV,
    destroyAccelerationStructureNV,
    getAccelerationStructureMemoryRequirementsNV,
    bindAccelerationStructureMemoryNV,
    cmdBuildAccelerationStructureNV,
    cmdCopyAccelerationStructureNV,
    cmdTraceRaysNV,
    createRayTracingPipelinesNV,
    getRayTracingShaderGroupHandlesKHR,
    getRayTracingShaderGroupHandlesNV,
    getAccelerationStructureHandleNV,
    cmdWriteAccelerationStructuresPropertiesNV,
    compileDeferredNV,
    getMemoryHostPointerPropertiesEXT,
    cmdWriteBufferMarkerAMD,
    getPhysicalDeviceCalibrateableTimeDomainsEXT,
    getCalibratedTimestampsEXT,
    cmdDrawMeshTasksNV,
    cmdDrawMeshTasksIndirectNV,
    cmdDrawMeshTasksIndirectCountNV,
    cmdSetExclusiveScissorEnableNV,
    cmdSetExclusiveScissorNV,
    cmdSetCheckpointNV,
    getQueueCheckpointDataNV,
    initializePerformanceApiINTEL,
    uninitializePerformanceApiINTEL,
    cmdSetPerformanceMarkerINTEL,
    cmdSetPerformanceStreamMarkerINTEL,
    cmdSetPerformanceOverrideINTEL,
    acquirePerformanceConfigurationINTEL,
    releasePerformanceConfigurationINTEL,
    queueSetPerformanceConfigurationINTEL,
    getPerformanceParameterINTEL,
    setLocalDimmingAMD,
    getBufferDeviceAddressEXT,
    getPhysicalDeviceToolPropertiesEXT,
    getPhysicalDeviceCooperativeMatrixPropertiesNV,
    getPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV,
    createHeadlessSurfaceEXT,
    cmdSetLineStippleEXT,
    resetQueryPoolEXT,
    cmdSetCullModeEXT,
    cmdSetFrontFaceEXT,
    cmdSetPrimitiveTopologyEXT,
    cmdSetViewportWithCountEXT,
    cmdSetScissorWithCountEXT,
    cmdBindVertexBuffers2EXT,
    cmdSetDepthTestEnableEXT,
    cmdSetDepthWriteEnableEXT,
    cmdSetDepthCompareOpEXT,
    cmdSetDepthBoundsTestEnableEXT,
    cmdSetStencilTestEnableEXT,
    cmdSetStencilOpEXT,
    copyMemoryToImageEXT,
    copyImageToMemoryEXT,
    copyImageToImageEXT,
    transitionImageLayoutEXT,
    getImageSubresourceLayout2EXT,
    releaseSwapchainImagesEXT,
    getGeneratedCommandsMemoryRequirementsNV,
    cmdPreprocessGeneratedCommandsNV,
    cmdExecuteGeneratedCommandsNV,
    cmdBindPipelineShaderGroupNV,
    createIndirectCommandsLayoutNV,
    destroyIndirectCommandsLayoutNV,
    cmdSetDepthBias2EXT,
    deviceMemoryReportCallbackEXT,
    acquireDrmDisplayEXT,
    getDrmDisplayEXT,
    createPrivateDataSlotEXT,
    destroyPrivateDataSlotEXT,
    setPrivateDataEXT,
    getPrivateDataEXT,
    createCudaModuleNV,
    getCudaModuleCacheNV,
    createCudaFunctionNV,
    destroyCudaModuleNV,
    destroyCudaFunctionNV,
    cmdCudaLaunchKernelNV,
    getDescriptorSetLayoutSizeEXT,
    getDescriptorSetLayoutBindingOffsetEXT,
    getDescriptorEXT,
    cmdBindDescriptorBuffersEXT,
    cmdSetDescriptorBufferOffsetsEXT,
    cmdBindDescriptorBufferEmbeddedSamplersEXT,
    getBufferOpaqueCaptureDescriptorDataEXT,
    getImageOpaqueCaptureDescriptorDataEXT,
    getImageViewOpaqueCaptureDescriptorDataEXT,
    getSamplerOpaqueCaptureDescriptorDataEXT,
    getAccelerationStructureOpaqueCaptureDescriptorDataEXT,
    cmdSetFragmentShadingRateEnumNV,
    getDeviceFaultInfoEXT,
    cmdSetVertexInputEXT,
    getDeviceSubpassShadingMaxWorkgroupSizeHUAWEI,
    cmdSubpassShadingHUAWEI,
    cmdBindInvocationMaskHUAWEI,
    getMemoryRemoteAddressNV,
    getPipelinePropertiesEXT,
    cmdSetPatchControlPointsEXT,
    cmdSetRasterizerDiscardEnableEXT,
    cmdSetDepthBiasEnableEXT,
    cmdSetLogicOpEXT,
    cmdSetPrimitiveRestartEnableEXT,
    cmdSetColorWriteEnableEXT,
    cmdDrawMultiEXT,
    cmdDrawMultiIndexedEXT,
    createMicromapEXT,
    destroyMicromapEXT,
    cmdBuildMicromapsEXT,
    buildMicromapsEXT,
    copyMicromapEXT,
    copyMicromapToMemoryEXT,
    copyMemoryToMicromapEXT,
    writeMicromapsPropertiesEXT,
    cmdCopyMicromapEXT,
    cmdCopyMicromapToMemoryEXT,
    cmdCopyMemoryToMicromapEXT,
    cmdWriteMicromapsPropertiesEXT,
    getDeviceMicromapCompatibilityEXT,
    getMicromapBuildSizesEXT,
    cmdDrawClusterHUAWEI,
    cmdDrawClusterIndirectHUAWEI,
    setDeviceMemoryPriorityEXT,
    getDescriptorSetLayoutHostMappingInfoVALVE,
    getDescriptorSetHostMappingVALVE,
    cmdCopyMemoryIndirectNV,
    cmdCopyMemoryToImageIndirectNV,
    cmdDecompressMemoryNV,
    cmdDecompressMemoryIndirectCountNV,
    getPipelineIndirectMemoryRequirementsNV,
    cmdUpdatePipelineIndirectBufferNV,
    getPipelineIndirectDeviceAddressNV,
    cmdSetDepthClampEnableEXT,
    cmdSetPolygonModeEXT,
    cmdSetRasterizationSamplesEXT,
    cmdSetSampleMaskEXT,
    cmdSetAlphaToCoverageEnableEXT,
    cmdSetAlphaToOneEnableEXT,
    cmdSetLogicOpEnableEXT,
    cmdSetColorBlendEnableEXT,
    cmdSetColorBlendEquationEXT,
    cmdSetColorWriteMaskEXT,
    cmdSetTessellationDomainOriginEXT,
    cmdSetRasterizationStreamEXT,
    cmdSetConservativeRasterizationModeEXT,
    cmdSetExtraPrimitiveOverestimationSizeEXT,
    cmdSetDepthClipEnableEXT,
    cmdSetSampleLocationsEnableEXT,
    cmdSetColorBlendAdvancedEXT,
    cmdSetProvokingVertexModeEXT,
    cmdSetLineRasterizationModeEXT,
    cmdSetLineStippleEnableEXT,
    cmdSetDepthClipNegativeOneToOneEXT,
    cmdSetViewportWScalingEnableNV,
    cmdSetViewportSwizzleNV,
    cmdSetCoverageToColorEnableNV,
    cmdSetCoverageToColorLocationNV,
    cmdSetCoverageModulationModeNV,
    cmdSetCoverageModulationTableEnableNV,
    cmdSetCoverageModulationTableNV,
    cmdSetShadingRateImageEnableNV,
    cmdSetRepresentativeFragmentTestEnableNV,
    cmdSetCoverageReductionModeNV,
    getInstanceProcAddrLUNARG,
    getShaderModuleIdentifierEXT,
    getShaderModuleCreateInfoIdentifierEXT,
    getPhysicalDeviceOpticalFlowImageFormatsNV,
    createOpticalFlowSessionNV,
    destroyOpticalFlowSessionNV,
    bindOpticalFlowSessionImageNV,
    cmdOpticalFlowExecuteNV,
    createShadersEXT,
    destroyShaderEXT,
    getShaderBinaryDataEXT,
    cmdBindShadersEXT,
    getFramebufferTilePropertiesQCOM,
    getDynamicRenderingTilePropertiesQCOM,
    setLatencySleepModeNV,
    latencySleepNV,
    setLatencyMarkerNV,
    getLatencyTimingsNV,
    queueNotifyOutOfBandNV,
    cmdSetAttachmentFeedbackLoopEnableEXT,
    createAccelerationStructureKHR,
    destroyAccelerationStructureKHR,
    cmdBuildAccelerationStructuresKHR,
    cmdBuildAccelerationStructuresIndirectKHR,
    buildAccelerationStructuresKHR,
    copyAccelerationStructureKHR,
    copyAccelerationStructureToMemoryKHR,
    copyMemoryToAccelerationStructureKHR,
    writeAccelerationStructuresPropertiesKHR,
    cmdCopyAccelerationStructureKHR,
    cmdCopyAccelerationStructureToMemoryKHR,
    cmdCopyMemoryToAccelerationStructureKHR,
    getAccelerationStructureDeviceAddressKHR,
    cmdWriteAccelerationStructuresPropertiesKHR,
    getDeviceAccelerationStructureCompatibilityKHR,
    getAccelerationStructureBuildSizesKHR,
    cmdTraceRaysKHR,
    createRayTracingPipelinesKHR,
    getRayTracingCaptureReplayShaderGroupHandlesKHR,
    cmdTraceRaysIndirectKHR,
    getRayTracingShaderGroupStackSizeKHR,
    cmdSetRayTracingPipelineStackSizeKHR,
    cmdDrawMeshTasksEXT,
    cmdDrawMeshTasksIndirectEXT,
    cmdDrawMeshTasksIndirectCountEXT,

    pub fn Proc(func: @This()) type {
        return struct {
            pub const name = std.fmt.comptimePrint("vk{c}{s}", .{ std.ascii.toUpper(@tagName(func)[0]), @tagName(func)[1..] });
            pub const PFN: type = switch (func) {
                .allocationFunction => c.PFN_vkAllocationFunction,
                .reallocationFunction => c.PFN_vkReallocationFunction,
                .freeFunction => c.PFN_vkFreeFunction,
                .internalAllocationNotification => c.PFN_vkInternalAllocationNotification,
                .internalFreeNotification => c.PFN_vkInternalFreeNotification,
                .createInstance => c.PFN_vkCreateInstance,
                .destroyInstance => c.PFN_vkDestroyInstance,
                .enumeratePhysicalDevices => c.PFN_vkEnumeratePhysicalDevices,
                .getPhysicalDeviceFeatures => c.PFN_vkGetPhysicalDeviceFeatures,
                .getPhysicalDeviceFormatProperties => c.PFN_vkGetPhysicalDeviceFormatProperties,
                .getPhysicalDeviceImageFormatProperties => c.PFN_vkGetPhysicalDeviceImageFormatProperties,
                .getPhysicalDeviceProperties => c.PFN_vkGetPhysicalDeviceProperties,
                .getPhysicalDeviceQueueFamilyProperties => c.PFN_vkGetPhysicalDeviceQueueFamilyProperties,
                .getPhysicalDeviceMemoryProperties => c.PFN_vkGetPhysicalDeviceMemoryProperties,
                .getInstanceProcAddr => c.PFN_vkGetInstanceProcAddr,
                .getDeviceProcAddr => c.PFN_vkGetDeviceProcAddr,
                .createDevice => c.PFN_vkCreateDevice,
                .destroyDevice => c.PFN_vkDestroyDevice,
                .enumerateInstanceExtensionProperties => c.PFN_vkEnumerateInstanceExtensionProperties,
                .enumerateDeviceExtensionProperties => c.PFN_vkEnumerateDeviceExtensionProperties,
                .enumerateInstanceLayerProperties => c.PFN_vkEnumerateInstanceLayerProperties,
                .enumerateDeviceLayerProperties => c.PFN_vkEnumerateDeviceLayerProperties,
                .getDeviceQueue => c.PFN_vkGetDeviceQueue,
                .queueSubmit => c.PFN_vkQueueSubmit,
                .queueWaitIdle => c.PFN_vkQueueWaitIdle,
                .deviceWaitIdle => c.PFN_vkDeviceWaitIdle,
                .allocateMemory => c.PFN_vkAllocateMemory,
                .freeMemory => c.PFN_vkFreeMemory,
                .mapMemory => c.PFN_vkMapMemory,
                .unmapMemory => c.PFN_vkUnmapMemory,
                .flushMappedMemoryRanges => c.PFN_vkFlushMappedMemoryRanges,
                .invalidateMappedMemoryRanges => c.PFN_vkInvalidateMappedMemoryRanges,
                .getDeviceMemoryCommitment => c.PFN_vkGetDeviceMemoryCommitment,
                .bindBufferMemory => c.PFN_vkBindBufferMemory,
                .bindImageMemory => c.PFN_vkBindImageMemory,
                .getBufferMemoryRequirements => c.PFN_vkGetBufferMemoryRequirements,
                .getImageMemoryRequirements => c.PFN_vkGetImageMemoryRequirements,
                .getImageSparseMemoryRequirements => c.PFN_vkGetImageSparseMemoryRequirements,
                .getPhysicalDeviceSparseImageFormatProperties => c.PFN_vkGetPhysicalDeviceSparseImageFormatProperties,
                .queueBindSparse => c.PFN_vkQueueBindSparse,
                .createFence => c.PFN_vkCreateFence,
                .destroyFence => c.PFN_vkDestroyFence,
                .resetFences => c.PFN_vkResetFences,
                .getFenceStatus => c.PFN_vkGetFenceStatus,
                .waitForFences => c.PFN_vkWaitForFences,
                .createSemaphore => c.PFN_vkCreateSemaphore,
                .destroySemaphore => c.PFN_vkDestroySemaphore,
                .createEvent => c.PFN_vkCreateEvent,
                .destroyEvent => c.PFN_vkDestroyEvent,
                .getEventStatus => c.PFN_vkGetEventStatus,
                .setEvent => c.PFN_vkSetEvent,
                .resetEvent => c.PFN_vkResetEvent,
                .createQueryPool => c.PFN_vkCreateQueryPool,
                .destroyQueryPool => c.PFN_vkDestroyQueryPool,
                .getQueryPoolResults => c.PFN_vkGetQueryPoolResults,
                .createBuffer => c.PFN_vkCreateBuffer,
                .destroyBuffer => c.PFN_vkDestroyBuffer,
                .createBufferView => c.PFN_vkCreateBufferView,
                .destroyBufferView => c.PFN_vkDestroyBufferView,
                .createImage => c.PFN_vkCreateImage,
                .destroyImage => c.PFN_vkDestroyImage,
                .getImageSubresourceLayout => c.PFN_vkGetImageSubresourceLayout,
                .createImageView => c.PFN_vkCreateImageView,
                .destroyImageView => c.PFN_vkDestroyImageView,
                .createShaderModule => c.PFN_vkCreateShaderModule,
                .destroyShaderModule => c.PFN_vkDestroyShaderModule,
                .createPipelineCache => c.PFN_vkCreatePipelineCache,
                .destroyPipelineCache => c.PFN_vkDestroyPipelineCache,
                .getPipelineCacheData => c.PFN_vkGetPipelineCacheData,
                .mergePipelineCaches => c.PFN_vkMergePipelineCaches,
                .createGraphicsPipelines => c.PFN_vkCreateGraphicsPipelines,
                .createComputePipelines => c.PFN_vkCreateComputePipelines,
                .destroyPipeline => c.PFN_vkDestroyPipeline,
                .createPipelineLayout => c.PFN_vkCreatePipelineLayout,
                .destroyPipelineLayout => c.PFN_vkDestroyPipelineLayout,
                .createSampler => c.PFN_vkCreateSampler,
                .destroySampler => c.PFN_vkDestroySampler,
                .createDescriptorSetLayout => c.PFN_vkCreateDescriptorSetLayout,
                .destroyDescriptorSetLayout => c.PFN_vkDestroyDescriptorSetLayout,
                .createDescriptorPool => c.PFN_vkCreateDescriptorPool,
                .destroyDescriptorPool => c.PFN_vkDestroyDescriptorPool,
                .resetDescriptorPool => c.PFN_vkResetDescriptorPool,
                .allocateDescriptorSets => c.PFN_vkAllocateDescriptorSets,
                .freeDescriptorSets => c.PFN_vkFreeDescriptorSets,
                .updateDescriptorSets => c.PFN_vkUpdateDescriptorSets,
                .createFramebuffer => c.PFN_vkCreateFramebuffer,
                .destroyFramebuffer => c.PFN_vkDestroyFramebuffer,
                .createRenderPass => c.PFN_vkCreateRenderPass,
                .destroyRenderPass => c.PFN_vkDestroyRenderPass,
                .getRenderAreaGranularity => c.PFN_vkGetRenderAreaGranularity,
                .createCommandPool => c.PFN_vkCreateCommandPool,
                .destroyCommandPool => c.PFN_vkDestroyCommandPool,
                .resetCommandPool => c.PFN_vkResetCommandPool,
                .allocateCommandBuffers => c.PFN_vkAllocateCommandBuffers,
                .freeCommandBuffers => c.PFN_vkFreeCommandBuffers,
                .beginCommandBuffer => c.PFN_vkBeginCommandBuffer,
                .endCommandBuffer => c.PFN_vkEndCommandBuffer,
                .resetCommandBuffer => c.PFN_vkResetCommandBuffer,
                .cmdBindPipeline => c.PFN_vkCmdBindPipeline,
                .cmdSetViewport => c.PFN_vkCmdSetViewport,
                .cmdSetScissor => c.PFN_vkCmdSetScissor,
                .cmdSetLineWidth => c.PFN_vkCmdSetLineWidth,
                .cmdSetDepthBias => c.PFN_vkCmdSetDepthBias,
                .cmdSetBlendConstants => c.PFN_vkCmdSetBlendConstants,
                .cmdSetDepthBounds => c.PFN_vkCmdSetDepthBounds,
                .cmdSetStencilCompareMask => c.PFN_vkCmdSetStencilCompareMask,
                .cmdSetStencilWriteMask => c.PFN_vkCmdSetStencilWriteMask,
                .cmdSetStencilReference => c.PFN_vkCmdSetStencilReference,
                .cmdBindDescriptorSets => c.PFN_vkCmdBindDescriptorSets,
                .cmdBindIndexBuffer => c.PFN_vkCmdBindIndexBuffer,
                .cmdBindVertexBuffers => c.PFN_vkCmdBindVertexBuffers,
                .cmdDraw => c.PFN_vkCmdDraw,
                .cmdDrawIndexed => c.PFN_vkCmdDrawIndexed,
                .cmdDrawIndirect => c.PFN_vkCmdDrawIndirect,
                .cmdDrawIndexedIndirect => c.PFN_vkCmdDrawIndexedIndirect,
                .cmdDispatch => c.PFN_vkCmdDispatch,
                .cmdDispatchIndirect => c.PFN_vkCmdDispatchIndirect,
                .cmdCopyBuffer => c.PFN_vkCmdCopyBuffer,
                .cmdCopyImage => c.PFN_vkCmdCopyImage,
                .cmdBlitImage => c.PFN_vkCmdBlitImage,
                .cmdCopyBufferToImage => c.PFN_vkCmdCopyBufferToImage,
                .cmdCopyImageToBuffer => c.PFN_vkCmdCopyImageToBuffer,
                .cmdUpdateBuffer => c.PFN_vkCmdUpdateBuffer,
                .cmdFillBuffer => c.PFN_vkCmdFillBuffer,
                .cmdClearColorImage => c.PFN_vkCmdClearColorImage,
                .cmdClearDepthStencilImage => c.PFN_vkCmdClearDepthStencilImage,
                .cmdClearAttachments => c.PFN_vkCmdClearAttachments,
                .cmdResolveImage => c.PFN_vkCmdResolveImage,
                .cmdSetEvent => c.PFN_vkCmdSetEvent,
                .cmdResetEvent => c.PFN_vkCmdResetEvent,
                .cmdWaitEvents => c.PFN_vkCmdWaitEvents,
                .cmdPipelineBarrier => c.PFN_vkCmdPipelineBarrier,
                .cmdBeginQuery => c.PFN_vkCmdBeginQuery,
                .cmdEndQuery => c.PFN_vkCmdEndQuery,
                .cmdResetQueryPool => c.PFN_vkCmdResetQueryPool,
                .cmdWriteTimestamp => c.PFN_vkCmdWriteTimestamp,
                .cmdCopyQueryPoolResults => c.PFN_vkCmdCopyQueryPoolResults,
                .cmdPushConstants => c.PFN_vkCmdPushConstants,
                .cmdBeginRenderPass => c.PFN_vkCmdBeginRenderPass,
                .cmdNextSubpass => c.PFN_vkCmdNextSubpass,
                .cmdEndRenderPass => c.PFN_vkCmdEndRenderPass,
                .cmdExecuteCommands => c.PFN_vkCmdExecuteCommands,
                .enumerateInstanceVersion => c.PFN_vkEnumerateInstanceVersion,
                .bindBufferMemory2 => c.PFN_vkBindBufferMemory2,
                .bindImageMemory2 => c.PFN_vkBindImageMemory2,
                .getDeviceGroupPeerMemoryFeatures => c.PFN_vkGetDeviceGroupPeerMemoryFeatures,
                .cmdSetDeviceMask => c.PFN_vkCmdSetDeviceMask,
                .cmdDispatchBase => c.PFN_vkCmdDispatchBase,
                .enumeratePhysicalDeviceGroups => c.PFN_vkEnumeratePhysicalDeviceGroups,
                .getImageMemoryRequirements2 => c.PFN_vkGetImageMemoryRequirements2,
                .getBufferMemoryRequirements2 => c.PFN_vkGetBufferMemoryRequirements2,
                .getImageSparseMemoryRequirements2 => c.PFN_vkGetImageSparseMemoryRequirements2,
                .getPhysicalDeviceFeatures2 => c.PFN_vkGetPhysicalDeviceFeatures2,
                .getPhysicalDeviceProperties2 => c.PFN_vkGetPhysicalDeviceProperties2,
                .getPhysicalDeviceFormatProperties2 => c.PFN_vkGetPhysicalDeviceFormatProperties2,
                .getPhysicalDeviceImageFormatProperties2 => c.PFN_vkGetPhysicalDeviceImageFormatProperties2,
                .getPhysicalDeviceQueueFamilyProperties2 => c.PFN_vkGetPhysicalDeviceQueueFamilyProperties2,
                .getPhysicalDeviceMemoryProperties2 => c.PFN_vkGetPhysicalDeviceMemoryProperties2,
                .getPhysicalDeviceSparseImageFormatProperties2 => c.PFN_vkGetPhysicalDeviceSparseImageFormatProperties2,
                .trimCommandPool => c.PFN_vkTrimCommandPool,
                .getDeviceQueue2 => c.PFN_vkGetDeviceQueue2,
                .createSamplerYcbcrConversion => c.PFN_vkCreateSamplerYcbcrConversion,
                .destroySamplerYcbcrConversion => c.PFN_vkDestroySamplerYcbcrConversion,
                .createDescriptorUpdateTemplate => c.PFN_vkCreateDescriptorUpdateTemplate,
                .destroyDescriptorUpdateTemplate => c.PFN_vkDestroyDescriptorUpdateTemplate,
                .updateDescriptorSetWithTemplate => c.PFN_vkUpdateDescriptorSetWithTemplate,
                .getPhysicalDeviceExternalBufferProperties => c.PFN_vkGetPhysicalDeviceExternalBufferProperties,
                .getPhysicalDeviceExternalFenceProperties => c.PFN_vkGetPhysicalDeviceExternalFenceProperties,
                .getPhysicalDeviceExternalSemaphoreProperties => c.PFN_vkGetPhysicalDeviceExternalSemaphoreProperties,
                .getDescriptorSetLayoutSupport => c.PFN_vkGetDescriptorSetLayoutSupport,
                .cmdDrawIndirectCount => c.PFN_vkCmdDrawIndirectCount,
                .cmdDrawIndexedIndirectCount => c.PFN_vkCmdDrawIndexedIndirectCount,
                .createRenderPass2 => c.PFN_vkCreateRenderPass2,
                .cmdBeginRenderPass2 => c.PFN_vkCmdBeginRenderPass2,
                .cmdNextSubpass2 => c.PFN_vkCmdNextSubpass2,
                .cmdEndRenderPass2 => c.PFN_vkCmdEndRenderPass2,
                .resetQueryPool => c.PFN_vkResetQueryPool,
                .getSemaphoreCounterValue => c.PFN_vkGetSemaphoreCounterValue,
                .waitSemaphores => c.PFN_vkWaitSemaphores,
                .signalSemaphore => c.PFN_vkSignalSemaphore,
                .getBufferDeviceAddress => c.PFN_vkGetBufferDeviceAddress,
                .getBufferOpaqueCaptureAddress => c.PFN_vkGetBufferOpaqueCaptureAddress,
                .getDeviceMemoryOpaqueCaptureAddress => c.PFN_vkGetDeviceMemoryOpaqueCaptureAddress,
                .getPhysicalDeviceToolProperties => c.PFN_vkGetPhysicalDeviceToolProperties,
                .createPrivateDataSlot => c.PFN_vkCreatePrivateDataSlot,
                .destroyPrivateDataSlot => c.PFN_vkDestroyPrivateDataSlot,
                .setPrivateData => c.PFN_vkSetPrivateData,
                .getPrivateData => c.PFN_vkGetPrivateData,
                .cmdSetEvent2 => c.PFN_vkCmdSetEvent2,
                .cmdResetEvent2 => c.PFN_vkCmdResetEvent2,
                .cmdWaitEvents2 => c.PFN_vkCmdWaitEvents2,
                .cmdPipelineBarrier2 => c.PFN_vkCmdPipelineBarrier2,
                .cmdWriteTimestamp2 => c.PFN_vkCmdWriteTimestamp2,
                .queueSubmit2 => c.PFN_vkQueueSubmit2,
                .cmdCopyBuffer2 => c.PFN_vkCmdCopyBuffer2,
                .cmdCopyImage2 => c.PFN_vkCmdCopyImage2,
                .cmdCopyBufferToImage2 => c.PFN_vkCmdCopyBufferToImage2,
                .cmdCopyImageToBuffer2 => c.PFN_vkCmdCopyImageToBuffer2,
                .cmdBlitImage2 => c.PFN_vkCmdBlitImage2,
                .cmdResolveImage2 => c.PFN_vkCmdResolveImage2,
                .cmdBeginRendering => c.PFN_vkCmdBeginRendering,
                .cmdEndRendering => c.PFN_vkCmdEndRendering,
                .cmdSetCullMode => c.PFN_vkCmdSetCullMode,
                .cmdSetFrontFace => c.PFN_vkCmdSetFrontFace,
                .cmdSetPrimitiveTopology => c.PFN_vkCmdSetPrimitiveTopology,
                .cmdSetViewportWithCount => c.PFN_vkCmdSetViewportWithCount,
                .cmdSetScissorWithCount => c.PFN_vkCmdSetScissorWithCount,
                .cmdBindVertexBuffers2 => c.PFN_vkCmdBindVertexBuffers2,
                .cmdSetDepthTestEnable => c.PFN_vkCmdSetDepthTestEnable,
                .cmdSetDepthWriteEnable => c.PFN_vkCmdSetDepthWriteEnable,
                .cmdSetDepthCompareOp => c.PFN_vkCmdSetDepthCompareOp,
                .cmdSetDepthBoundsTestEnable => c.PFN_vkCmdSetDepthBoundsTestEnable,
                .cmdSetStencilTestEnable => c.PFN_vkCmdSetStencilTestEnable,
                .cmdSetStencilOp => c.PFN_vkCmdSetStencilOp,
                .cmdSetRasterizerDiscardEnable => c.PFN_vkCmdSetRasterizerDiscardEnable,
                .cmdSetDepthBiasEnable => c.PFN_vkCmdSetDepthBiasEnable,
                .cmdSetPrimitiveRestartEnable => c.PFN_vkCmdSetPrimitiveRestartEnable,
                .getDeviceBufferMemoryRequirements => c.PFN_vkGetDeviceBufferMemoryRequirements,
                .getDeviceImageMemoryRequirements => c.PFN_vkGetDeviceImageMemoryRequirements,
                .getDeviceImageSparseMemoryRequirements => c.PFN_vkGetDeviceImageSparseMemoryRequirements,
                .destroySurfaceKHR => c.PFN_vkDestroySurfaceKHR,
                .getPhysicalDeviceSurfaceSupportKHR => c.PFN_vkGetPhysicalDeviceSurfaceSupportKHR,
                .getPhysicalDeviceSurfaceCapabilitiesKHR => c.PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR,
                .getPhysicalDeviceSurfaceFormatsKHR => c.PFN_vkGetPhysicalDeviceSurfaceFormatsKHR,
                .getPhysicalDeviceSurfacePresentModesKHR => c.PFN_vkGetPhysicalDeviceSurfacePresentModesKHR,
                .createSwapchainKHR => c.PFN_vkCreateSwapchainKHR,
                .destroySwapchainKHR => c.PFN_vkDestroySwapchainKHR,
                .getSwapchainImagesKHR => c.PFN_vkGetSwapchainImagesKHR,
                .acquireNextImageKHR => c.PFN_vkAcquireNextImageKHR,
                .queuePresentKHR => c.PFN_vkQueuePresentKHR,
                .getDeviceGroupPresentCapabilitiesKHR => c.PFN_vkGetDeviceGroupPresentCapabilitiesKHR,
                .getDeviceGroupSurfacePresentModesKHR => c.PFN_vkGetDeviceGroupSurfacePresentModesKHR,
                .getPhysicalDevicePresentRectanglesKHR => c.PFN_vkGetPhysicalDevicePresentRectanglesKHR,
                .acquireNextImage2KHR => c.PFN_vkAcquireNextImage2KHR,
                .getPhysicalDeviceDisplayPropertiesKHR => c.PFN_vkGetPhysicalDeviceDisplayPropertiesKHR,
                .getPhysicalDeviceDisplayPlanePropertiesKHR => c.PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR,
                .getDisplayPlaneSupportedDisplaysKHR => c.PFN_vkGetDisplayPlaneSupportedDisplaysKHR,
                .getDisplayModePropertiesKHR => c.PFN_vkGetDisplayModePropertiesKHR,
                .createDisplayModeKHR => c.PFN_vkCreateDisplayModeKHR,
                .getDisplayPlaneCapabilitiesKHR => c.PFN_vkGetDisplayPlaneCapabilitiesKHR,
                .createDisplayPlaneSurfaceKHR => c.PFN_vkCreateDisplayPlaneSurfaceKHR,
                .createSharedSwapchainsKHR => c.PFN_vkCreateSharedSwapchainsKHR,
                .getPhysicalDeviceVideoCapabilitiesKHR => c.PFN_vkGetPhysicalDeviceVideoCapabilitiesKHR,
                .getPhysicalDeviceVideoFormatPropertiesKHR => c.PFN_vkGetPhysicalDeviceVideoFormatPropertiesKHR,
                .createVideoSessionKHR => c.PFN_vkCreateVideoSessionKHR,
                .destroyVideoSessionKHR => c.PFN_vkDestroyVideoSessionKHR,
                .getVideoSessionMemoryRequirementsKHR => c.PFN_vkGetVideoSessionMemoryRequirementsKHR,
                .bindVideoSessionMemoryKHR => c.PFN_vkBindVideoSessionMemoryKHR,
                .createVideoSessionParametersKHR => c.PFN_vkCreateVideoSessionParametersKHR,
                .updateVideoSessionParametersKHR => c.PFN_vkUpdateVideoSessionParametersKHR,
                .destroyVideoSessionParametersKHR => c.PFN_vkDestroyVideoSessionParametersKHR,
                .cmdBeginVideoCodingKHR => c.PFN_vkCmdBeginVideoCodingKHR,
                .cmdEndVideoCodingKHR => c.PFN_vkCmdEndVideoCodingKHR,
                .cmdControlVideoCodingKHR => c.PFN_vkCmdControlVideoCodingKHR,
                .cmdDecodeVideoKHR => c.PFN_vkCmdDecodeVideoKHR,
                .cmdBeginRenderingKHR => c.PFN_vkCmdBeginRenderingKHR,
                .cmdEndRenderingKHR => c.PFN_vkCmdEndRenderingKHR,
                .getPhysicalDeviceFeatures2KHR => c.PFN_vkGetPhysicalDeviceFeatures2KHR,
                .getPhysicalDeviceProperties2KHR => c.PFN_vkGetPhysicalDeviceProperties2KHR,
                .getPhysicalDeviceFormatProperties2KHR => c.PFN_vkGetPhysicalDeviceFormatProperties2KHR,
                .getPhysicalDeviceImageFormatProperties2KHR => c.PFN_vkGetPhysicalDeviceImageFormatProperties2KHR,
                .getPhysicalDeviceQueueFamilyProperties2KHR => c.PFN_vkGetPhysicalDeviceQueueFamilyProperties2KHR,
                .getPhysicalDeviceMemoryProperties2KHR => c.PFN_vkGetPhysicalDeviceMemoryProperties2KHR,
                .getPhysicalDeviceSparseImageFormatProperties2KHR => c.PFN_vkGetPhysicalDeviceSparseImageFormatProperties2KHR,
                .getDeviceGroupPeerMemoryFeaturesKHR => c.PFN_vkGetDeviceGroupPeerMemoryFeaturesKHR,
                .cmdSetDeviceMaskKHR => c.PFN_vkCmdSetDeviceMaskKHR,
                .cmdDispatchBaseKHR => c.PFN_vkCmdDispatchBaseKHR,
                .trimCommandPoolKHR => c.PFN_vkTrimCommandPoolKHR,
                .enumeratePhysicalDeviceGroupsKHR => c.PFN_vkEnumeratePhysicalDeviceGroupsKHR,
                .getPhysicalDeviceExternalBufferPropertiesKHR => c.PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR,
                .getMemoryFdKHR => c.PFN_vkGetMemoryFdKHR,
                .getMemoryFdPropertiesKHR => c.PFN_vkGetMemoryFdPropertiesKHR,
                .getPhysicalDeviceExternalSemaphorePropertiesKHR => c.PFN_vkGetPhysicalDeviceExternalSemaphorePropertiesKHR,
                .importSemaphoreFdKHR => c.PFN_vkImportSemaphoreFdKHR,
                .getSemaphoreFdKHR => c.PFN_vkGetSemaphoreFdKHR,
                .cmdPushDescriptorSetKHR => c.PFN_vkCmdPushDescriptorSetKHR,
                .cmdPushDescriptorSetWithTemplateKHR => c.PFN_vkCmdPushDescriptorSetWithTemplateKHR,
                .createDescriptorUpdateTemplateKHR => c.PFN_vkCreateDescriptorUpdateTemplateKHR,
                .destroyDescriptorUpdateTemplateKHR => c.PFN_vkDestroyDescriptorUpdateTemplateKHR,
                .updateDescriptorSetWithTemplateKHR => c.PFN_vkUpdateDescriptorSetWithTemplateKHR,
                .createRenderPass2KHR => c.PFN_vkCreateRenderPass2KHR,
                .cmdBeginRenderPass2KHR => c.PFN_vkCmdBeginRenderPass2KHR,
                .cmdNextSubpass2KHR => c.PFN_vkCmdNextSubpass2KHR,
                .cmdEndRenderPass2KHR => c.PFN_vkCmdEndRenderPass2KHR,
                .getSwapchainStatusKHR => c.PFN_vkGetSwapchainStatusKHR,
                .getPhysicalDeviceExternalFencePropertiesKHR => c.PFN_vkGetPhysicalDeviceExternalFencePropertiesKHR,
                .importFenceFdKHR => c.PFN_vkImportFenceFdKHR,
                .getFenceFdKHR => c.PFN_vkGetFenceFdKHR,
                .enumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR => c.PFN_vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR,
                .getPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR => c.PFN_vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR,
                .acquireProfilingLockKHR => c.PFN_vkAcquireProfilingLockKHR,
                .releaseProfilingLockKHR => c.PFN_vkReleaseProfilingLockKHR,
                .getPhysicalDeviceSurfaceCapabilities2KHR => c.PFN_vkGetPhysicalDeviceSurfaceCapabilities2KHR,
                .getPhysicalDeviceSurfaceFormats2KHR => c.PFN_vkGetPhysicalDeviceSurfaceFormats2KHR,
                .getPhysicalDeviceDisplayProperties2KHR => c.PFN_vkGetPhysicalDeviceDisplayProperties2KHR,
                .getPhysicalDeviceDisplayPlaneProperties2KHR => c.PFN_vkGetPhysicalDeviceDisplayPlaneProperties2KHR,
                .getDisplayModeProperties2KHR => c.PFN_vkGetDisplayModeProperties2KHR,
                .getDisplayPlaneCapabilities2KHR => c.PFN_vkGetDisplayPlaneCapabilities2KHR,
                .getImageMemoryRequirements2KHR => c.PFN_vkGetImageMemoryRequirements2KHR,
                .getBufferMemoryRequirements2KHR => c.PFN_vkGetBufferMemoryRequirements2KHR,
                .getImageSparseMemoryRequirements2KHR => c.PFN_vkGetImageSparseMemoryRequirements2KHR,
                .createSamplerYcbcrConversionKHR => c.PFN_vkCreateSamplerYcbcrConversionKHR,
                .destroySamplerYcbcrConversionKHR => c.PFN_vkDestroySamplerYcbcrConversionKHR,
                .bindBufferMemory2KHR => c.PFN_vkBindBufferMemory2KHR,
                .bindImageMemory2KHR => c.PFN_vkBindImageMemory2KHR,
                .getDescriptorSetLayoutSupportKHR => c.PFN_vkGetDescriptorSetLayoutSupportKHR,
                .cmdDrawIndirectCountKHR => c.PFN_vkCmdDrawIndirectCountKHR,
                .cmdDrawIndexedIndirectCountKHR => c.PFN_vkCmdDrawIndexedIndirectCountKHR,
                .getSemaphoreCounterValueKHR => c.PFN_vkGetSemaphoreCounterValueKHR,
                .waitSemaphoresKHR => c.PFN_vkWaitSemaphoresKHR,
                .signalSemaphoreKHR => c.PFN_vkSignalSemaphoreKHR,
                .getPhysicalDeviceFragmentShadingRatesKHR => c.PFN_vkGetPhysicalDeviceFragmentShadingRatesKHR,
                .cmdSetFragmentShadingRateKHR => c.PFN_vkCmdSetFragmentShadingRateKHR,
                .cmdSetRenderingAttachmentLocationsKHR => c.PFN_vkCmdSetRenderingAttachmentLocationsKHR,
                .cmdSetRenderingInputAttachmentIndicesKHR => c.PFN_vkCmdSetRenderingInputAttachmentIndicesKHR,
                .waitForPresentKHR => c.PFN_vkWaitForPresentKHR,
                .getBufferDeviceAddressKHR => c.PFN_vkGetBufferDeviceAddressKHR,
                .getBufferOpaqueCaptureAddressKHR => c.PFN_vkGetBufferOpaqueCaptureAddressKHR,
                .getDeviceMemoryOpaqueCaptureAddressKHR => c.PFN_vkGetDeviceMemoryOpaqueCaptureAddressKHR,
                .createDeferredOperationKHR => c.PFN_vkCreateDeferredOperationKHR,
                .destroyDeferredOperationKHR => c.PFN_vkDestroyDeferredOperationKHR,
                .getDeferredOperationMaxConcurrencyKHR => c.PFN_vkGetDeferredOperationMaxConcurrencyKHR,
                .getDeferredOperationResultKHR => c.PFN_vkGetDeferredOperationResultKHR,
                .deferredOperationJoinKHR => c.PFN_vkDeferredOperationJoinKHR,
                .getPipelineExecutablePropertiesKHR => c.PFN_vkGetPipelineExecutablePropertiesKHR,
                .getPipelineExecutableStatisticsKHR => c.PFN_vkGetPipelineExecutableStatisticsKHR,
                .getPipelineExecutableInternalRepresentationsKHR => c.PFN_vkGetPipelineExecutableInternalRepresentationsKHR,
                .mapMemory2KHR => c.PFN_vkMapMemory2KHR,
                .unmapMemory2KHR => c.PFN_vkUnmapMemory2KHR,
                .getPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR => c.PFN_vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR,
                .getEncodedVideoSessionParametersKHR => c.PFN_vkGetEncodedVideoSessionParametersKHR,
                .cmdEncodeVideoKHR => c.PFN_vkCmdEncodeVideoKHR,
                .cmdSetEvent2KHR => c.PFN_vkCmdSetEvent2KHR,
                .cmdResetEvent2KHR => c.PFN_vkCmdResetEvent2KHR,
                .cmdWaitEvents2KHR => c.PFN_vkCmdWaitEvents2KHR,
                .cmdPipelineBarrier2KHR => c.PFN_vkCmdPipelineBarrier2KHR,
                .cmdWriteTimestamp2KHR => c.PFN_vkCmdWriteTimestamp2KHR,
                .queueSubmit2KHR => c.PFN_vkQueueSubmit2KHR,
                .cmdWriteBufferMarker2AMD => c.PFN_vkCmdWriteBufferMarker2AMD,
                .getQueueCheckpointData2NV => c.PFN_vkGetQueueCheckpointData2NV,
                .cmdCopyBuffer2KHR => c.PFN_vkCmdCopyBuffer2KHR,
                .cmdCopyImage2KHR => c.PFN_vkCmdCopyImage2KHR,
                .cmdCopyBufferToImage2KHR => c.PFN_vkCmdCopyBufferToImage2KHR,
                .cmdCopyImageToBuffer2KHR => c.PFN_vkCmdCopyImageToBuffer2KHR,
                .cmdBlitImage2KHR => c.PFN_vkCmdBlitImage2KHR,
                .cmdResolveImage2KHR => c.PFN_vkCmdResolveImage2KHR,
                .cmdTraceRaysIndirect2KHR => c.PFN_vkCmdTraceRaysIndirect2KHR,
                .getDeviceBufferMemoryRequirementsKHR => c.PFN_vkGetDeviceBufferMemoryRequirementsKHR,
                .getDeviceImageMemoryRequirementsKHR => c.PFN_vkGetDeviceImageMemoryRequirementsKHR,
                .getDeviceImageSparseMemoryRequirementsKHR => c.PFN_vkGetDeviceImageSparseMemoryRequirementsKHR,
                .cmdBindIndexBuffer2KHR => c.PFN_vkCmdBindIndexBuffer2KHR,
                .getRenderingAreaGranularityKHR => c.PFN_vkGetRenderingAreaGranularityKHR,
                .getDeviceImageSubresourceLayoutKHR => c.PFN_vkGetDeviceImageSubresourceLayoutKHR,
                .getImageSubresourceLayout2KHR => c.PFN_vkGetImageSubresourceLayout2KHR,
                .getPhysicalDeviceCooperativeMatrixPropertiesKHR => c.PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR,
                .cmdSetLineStippleKHR => c.PFN_vkCmdSetLineStippleKHR,
                .getPhysicalDeviceCalibrateableTimeDomainsKHR => c.PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR,
                .getCalibratedTimestampsKHR => c.PFN_vkGetCalibratedTimestampsKHR,
                .cmdBindDescriptorSets2KHR => c.PFN_vkCmdBindDescriptorSets2KHR,
                .cmdPushConstants2KHR => c.PFN_vkCmdPushConstants2KHR,
                .cmdPushDescriptorSet2KHR => c.PFN_vkCmdPushDescriptorSet2KHR,
                .cmdPushDescriptorSetWithTemplate2KHR => c.PFN_vkCmdPushDescriptorSetWithTemplate2KHR,
                .cmdSetDescriptorBufferOffsets2EXT => c.PFN_vkCmdSetDescriptorBufferOffsets2EXT,
                .cmdBindDescriptorBufferEmbeddedSamplers2EXT => c.PFN_vkCmdBindDescriptorBufferEmbeddedSamplers2EXT,
                .debugReportCallbackEXT => c.PFN_vkDebugReportCallbackEXT,
                .createDebugReportCallbackEXT => c.PFN_vkCreateDebugReportCallbackEXT,
                .destroyDebugReportCallbackEXT => c.PFN_vkDestroyDebugReportCallbackEXT,
                .debugReportMessageEXT => c.PFN_vkDebugReportMessageEXT,
                .debugMarkerSetObjectTagEXT => c.PFN_vkDebugMarkerSetObjectTagEXT,
                .debugMarkerSetObjectNameEXT => c.PFN_vkDebugMarkerSetObjectNameEXT,
                .cmdDebugMarkerBeginEXT => c.PFN_vkCmdDebugMarkerBeginEXT,
                .cmdDebugMarkerEndEXT => c.PFN_vkCmdDebugMarkerEndEXT,
                .cmdDebugMarkerInsertEXT => c.PFN_vkCmdDebugMarkerInsertEXT,
                .cmdBindTransformFeedbackBuffersEXT => c.PFN_vkCmdBindTransformFeedbackBuffersEXT,
                .cmdBeginTransformFeedbackEXT => c.PFN_vkCmdBeginTransformFeedbackEXT,
                .cmdEndTransformFeedbackEXT => c.PFN_vkCmdEndTransformFeedbackEXT,
                .cmdBeginQueryIndexedEXT => c.PFN_vkCmdBeginQueryIndexedEXT,
                .cmdEndQueryIndexedEXT => c.PFN_vkCmdEndQueryIndexedEXT,
                .cmdDrawIndirectByteCountEXT => c.PFN_vkCmdDrawIndirectByteCountEXT,
                .createCuModuleNVX => c.PFN_vkCreateCuModuleNVX,
                .createCuFunctionNVX => c.PFN_vkCreateCuFunctionNVX,
                .destroyCuModuleNVX => c.PFN_vkDestroyCuModuleNVX,
                .destroyCuFunctionNVX => c.PFN_vkDestroyCuFunctionNVX,
                .cmdCuLaunchKernelNVX => c.PFN_vkCmdCuLaunchKernelNVX,
                .getImageViewHandleNVX => c.PFN_vkGetImageViewHandleNVX,
                .getImageViewAddressNVX => c.PFN_vkGetImageViewAddressNVX,
                .cmdDrawIndirectCountAMD => c.PFN_vkCmdDrawIndirectCountAMD,
                .cmdDrawIndexedIndirectCountAMD => c.PFN_vkCmdDrawIndexedIndirectCountAMD,
                .getShaderInfoAMD => c.PFN_vkGetShaderInfoAMD,
                .getPhysicalDeviceExternalImageFormatPropertiesNV => c.PFN_vkGetPhysicalDeviceExternalImageFormatPropertiesNV,
                .cmdBeginConditionalRenderingEXT => c.PFN_vkCmdBeginConditionalRenderingEXT,
                .cmdEndConditionalRenderingEXT => c.PFN_vkCmdEndConditionalRenderingEXT,
                .cmdSetViewportWScalingNV => c.PFN_vkCmdSetViewportWScalingNV,
                .releaseDisplayEXT => c.PFN_vkReleaseDisplayEXT,
                .getPhysicalDeviceSurfaceCapabilities2EXT => c.PFN_vkGetPhysicalDeviceSurfaceCapabilities2EXT,
                .displayPowerControlEXT => c.PFN_vkDisplayPowerControlEXT,
                .registerDeviceEventEXT => c.PFN_vkRegisterDeviceEventEXT,
                .registerDisplayEventEXT => c.PFN_vkRegisterDisplayEventEXT,
                .getSwapchainCounterEXT => c.PFN_vkGetSwapchainCounterEXT,
                .getRefreshCycleDurationGOOGLE => c.PFN_vkGetRefreshCycleDurationGOOGLE,
                .getPastPresentationTimingGOOGLE => c.PFN_vkGetPastPresentationTimingGOOGLE,
                .cmdSetDiscardRectangleEXT => c.PFN_vkCmdSetDiscardRectangleEXT,
                .cmdSetDiscardRectangleEnableEXT => c.PFN_vkCmdSetDiscardRectangleEnableEXT,
                .cmdSetDiscardRectangleModeEXT => c.PFN_vkCmdSetDiscardRectangleModeEXT,
                .setHdrMetadataEXT => c.PFN_vkSetHdrMetadataEXT,
                .debugUtilsMessengerCallbackEXT => c.PFN_vkDebugUtilsMessengerCallbackEXT,
                .setDebugUtilsObjectNameEXT => c.PFN_vkSetDebugUtilsObjectNameEXT,
                .setDebugUtilsObjectTagEXT => c.PFN_vkSetDebugUtilsObjectTagEXT,
                .queueBeginDebugUtilsLabelEXT => c.PFN_vkQueueBeginDebugUtilsLabelEXT,
                .queueEndDebugUtilsLabelEXT => c.PFN_vkQueueEndDebugUtilsLabelEXT,
                .queueInsertDebugUtilsLabelEXT => c.PFN_vkQueueInsertDebugUtilsLabelEXT,
                .cmdBeginDebugUtilsLabelEXT => c.PFN_vkCmdBeginDebugUtilsLabelEXT,
                .cmdEndDebugUtilsLabelEXT => c.PFN_vkCmdEndDebugUtilsLabelEXT,
                .cmdInsertDebugUtilsLabelEXT => c.PFN_vkCmdInsertDebugUtilsLabelEXT,
                .createDebugUtilsMessengerEXT => c.PFN_vkCreateDebugUtilsMessengerEXT,
                .destroyDebugUtilsMessengerEXT => c.PFN_vkDestroyDebugUtilsMessengerEXT,
                .submitDebugUtilsMessageEXT => c.PFN_vkSubmitDebugUtilsMessageEXT,
                .cmdSetSampleLocationsEXT => c.PFN_vkCmdSetSampleLocationsEXT,
                .getPhysicalDeviceMultisamplePropertiesEXT => c.PFN_vkGetPhysicalDeviceMultisamplePropertiesEXT,
                .getImageDrmFormatModifierPropertiesEXT => c.PFN_vkGetImageDrmFormatModifierPropertiesEXT,
                .createValidationCacheEXT => c.PFN_vkCreateValidationCacheEXT,
                .destroyValidationCacheEXT => c.PFN_vkDestroyValidationCacheEXT,
                .mergeValidationCachesEXT => c.PFN_vkMergeValidationCachesEXT,
                .getValidationCacheDataEXT => c.PFN_vkGetValidationCacheDataEXT,
                .cmdBindShadingRateImageNV => c.PFN_vkCmdBindShadingRateImageNV,
                .cmdSetViewportShadingRatePaletteNV => c.PFN_vkCmdSetViewportShadingRatePaletteNV,
                .cmdSetCoarseSampleOrderNV => c.PFN_vkCmdSetCoarseSampleOrderNV,
                .createAccelerationStructureNV => c.PFN_vkCreateAccelerationStructureNV,
                .destroyAccelerationStructureNV => c.PFN_vkDestroyAccelerationStructureNV,
                .getAccelerationStructureMemoryRequirementsNV => c.PFN_vkGetAccelerationStructureMemoryRequirementsNV,
                .bindAccelerationStructureMemoryNV => c.PFN_vkBindAccelerationStructureMemoryNV,
                .cmdBuildAccelerationStructureNV => c.PFN_vkCmdBuildAccelerationStructureNV,
                .cmdCopyAccelerationStructureNV => c.PFN_vkCmdCopyAccelerationStructureNV,
                .cmdTraceRaysNV => c.PFN_vkCmdTraceRaysNV,
                .createRayTracingPipelinesNV => c.PFN_vkCreateRayTracingPipelinesNV,
                .getRayTracingShaderGroupHandlesKHR => c.PFN_vkGetRayTracingShaderGroupHandlesKHR,
                .getRayTracingShaderGroupHandlesNV => c.PFN_vkGetRayTracingShaderGroupHandlesNV,
                .getAccelerationStructureHandleNV => c.PFN_vkGetAccelerationStructureHandleNV,
                .cmdWriteAccelerationStructuresPropertiesNV => c.PFN_vkCmdWriteAccelerationStructuresPropertiesNV,
                .compileDeferredNV => c.PFN_vkCompileDeferredNV,
                .getMemoryHostPointerPropertiesEXT => c.PFN_vkGetMemoryHostPointerPropertiesEXT,
                .cmdWriteBufferMarkerAMD => c.PFN_vkCmdWriteBufferMarkerAMD,
                .getPhysicalDeviceCalibrateableTimeDomainsEXT => c.PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsEXT,
                .getCalibratedTimestampsEXT => c.PFN_vkGetCalibratedTimestampsEXT,
                .cmdDrawMeshTasksNV => c.PFN_vkCmdDrawMeshTasksNV,
                .cmdDrawMeshTasksIndirectNV => c.PFN_vkCmdDrawMeshTasksIndirectNV,
                .cmdDrawMeshTasksIndirectCountNV => c.PFN_vkCmdDrawMeshTasksIndirectCountNV,
                .cmdSetExclusiveScissorEnableNV => c.PFN_vkCmdSetExclusiveScissorEnableNV,
                .cmdSetExclusiveScissorNV => c.PFN_vkCmdSetExclusiveScissorNV,
                .cmdSetCheckpointNV => c.PFN_vkCmdSetCheckpointNV,
                .getQueueCheckpointDataNV => c.PFN_vkGetQueueCheckpointDataNV,
                .initializePerformanceApiINTEL => c.PFN_vkInitializePerformanceApiINTEL,
                .uninitializePerformanceApiINTEL => c.PFN_vkUninitializePerformanceApiINTEL,
                .cmdSetPerformanceMarkerINTEL => c.PFN_vkCmdSetPerformanceMarkerINTEL,
                .cmdSetPerformanceStreamMarkerINTEL => c.PFN_vkCmdSetPerformanceStreamMarkerINTEL,
                .cmdSetPerformanceOverrideINTEL => c.PFN_vkCmdSetPerformanceOverrideINTEL,
                .acquirePerformanceConfigurationINTEL => c.PFN_vkAcquirePerformanceConfigurationINTEL,
                .releasePerformanceConfigurationINTEL => c.PFN_vkReleasePerformanceConfigurationINTEL,
                .queueSetPerformanceConfigurationINTEL => c.PFN_vkQueueSetPerformanceConfigurationINTEL,
                .getPerformanceParameterINTEL => c.PFN_vkGetPerformanceParameterINTEL,
                .setLocalDimmingAMD => c.PFN_vkSetLocalDimmingAMD,
                .getBufferDeviceAddressEXT => c.PFN_vkGetBufferDeviceAddressEXT,
                .getPhysicalDeviceToolPropertiesEXT => c.PFN_vkGetPhysicalDeviceToolPropertiesEXT,
                .getPhysicalDeviceCooperativeMatrixPropertiesNV => c.PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesNV,
                .getPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV => c.PFN_vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV,
                .createHeadlessSurfaceEXT => c.PFN_vkCreateHeadlessSurfaceEXT,
                .cmdSetLineStippleEXT => c.PFN_vkCmdSetLineStippleEXT,
                .resetQueryPoolEXT => c.PFN_vkResetQueryPoolEXT,
                .cmdSetCullModeEXT => c.PFN_vkCmdSetCullModeEXT,
                .cmdSetFrontFaceEXT => c.PFN_vkCmdSetFrontFaceEXT,
                .cmdSetPrimitiveTopologyEXT => c.PFN_vkCmdSetPrimitiveTopologyEXT,
                .cmdSetViewportWithCountEXT => c.PFN_vkCmdSetViewportWithCountEXT,
                .cmdSetScissorWithCountEXT => c.PFN_vkCmdSetScissorWithCountEXT,
                .cmdBindVertexBuffers2EXT => c.PFN_vkCmdBindVertexBuffers2EXT,
                .cmdSetDepthTestEnableEXT => c.PFN_vkCmdSetDepthTestEnableEXT,
                .cmdSetDepthWriteEnableEXT => c.PFN_vkCmdSetDepthWriteEnableEXT,
                .cmdSetDepthCompareOpEXT => c.PFN_vkCmdSetDepthCompareOpEXT,
                .cmdSetDepthBoundsTestEnableEXT => c.PFN_vkCmdSetDepthBoundsTestEnableEXT,
                .cmdSetStencilTestEnableEXT => c.PFN_vkCmdSetStencilTestEnableEXT,
                .cmdSetStencilOpEXT => c.PFN_vkCmdSetStencilOpEXT,
                .copyMemoryToImageEXT => c.PFN_vkCopyMemoryToImageEXT,
                .copyImageToMemoryEXT => c.PFN_vkCopyImageToMemoryEXT,
                .copyImageToImageEXT => c.PFN_vkCopyImageToImageEXT,
                .transitionImageLayoutEXT => c.PFN_vkTransitionImageLayoutEXT,
                .getImageSubresourceLayout2EXT => c.PFN_vkGetImageSubresourceLayout2EXT,
                .releaseSwapchainImagesEXT => c.PFN_vkReleaseSwapchainImagesEXT,
                .getGeneratedCommandsMemoryRequirementsNV => c.PFN_vkGetGeneratedCommandsMemoryRequirementsNV,
                .cmdPreprocessGeneratedCommandsNV => c.PFN_vkCmdPreprocessGeneratedCommandsNV,
                .cmdExecuteGeneratedCommandsNV => c.PFN_vkCmdExecuteGeneratedCommandsNV,
                .cmdBindPipelineShaderGroupNV => c.PFN_vkCmdBindPipelineShaderGroupNV,
                .createIndirectCommandsLayoutNV => c.PFN_vkCreateIndirectCommandsLayoutNV,
                .destroyIndirectCommandsLayoutNV => c.PFN_vkDestroyIndirectCommandsLayoutNV,
                .cmdSetDepthBias2EXT => c.PFN_vkCmdSetDepthBias2EXT,
                .deviceMemoryReportCallbackEXT => c.PFN_vkDeviceMemoryReportCallbackEXT,
                .acquireDrmDisplayEXT => c.PFN_vkAcquireDrmDisplayEXT,
                .getDrmDisplayEXT => c.PFN_vkGetDrmDisplayEXT,
                .createPrivateDataSlotEXT => c.PFN_vkCreatePrivateDataSlotEXT,
                .destroyPrivateDataSlotEXT => c.PFN_vkDestroyPrivateDataSlotEXT,
                .setPrivateDataEXT => c.PFN_vkSetPrivateDataEXT,
                .getPrivateDataEXT => c.PFN_vkGetPrivateDataEXT,
                .createCudaModuleNV => c.PFN_vkCreateCudaModuleNV,
                .getCudaModuleCacheNV => c.PFN_vkGetCudaModuleCacheNV,
                .createCudaFunctionNV => c.PFN_vkCreateCudaFunctionNV,
                .destroyCudaModuleNV => c.PFN_vkDestroyCudaModuleNV,
                .destroyCudaFunctionNV => c.PFN_vkDestroyCudaFunctionNV,
                .cmdCudaLaunchKernelNV => c.PFN_vkCmdCudaLaunchKernelNV,
                .getDescriptorSetLayoutSizeEXT => c.PFN_vkGetDescriptorSetLayoutSizeEXT,
                .getDescriptorSetLayoutBindingOffsetEXT => c.PFN_vkGetDescriptorSetLayoutBindingOffsetEXT,
                .getDescriptorEXT => c.PFN_vkGetDescriptorEXT,
                .cmdBindDescriptorBuffersEXT => c.PFN_vkCmdBindDescriptorBuffersEXT,
                .cmdSetDescriptorBufferOffsetsEXT => c.PFN_vkCmdSetDescriptorBufferOffsetsEXT,
                .cmdBindDescriptorBufferEmbeddedSamplersEXT => c.PFN_vkCmdBindDescriptorBufferEmbeddedSamplersEXT,
                .getBufferOpaqueCaptureDescriptorDataEXT => c.PFN_vkGetBufferOpaqueCaptureDescriptorDataEXT,
                .getImageOpaqueCaptureDescriptorDataEXT => c.PFN_vkGetImageOpaqueCaptureDescriptorDataEXT,
                .getImageViewOpaqueCaptureDescriptorDataEXT => c.PFN_vkGetImageViewOpaqueCaptureDescriptorDataEXT,
                .getSamplerOpaqueCaptureDescriptorDataEXT => c.PFN_vkGetSamplerOpaqueCaptureDescriptorDataEXT,
                .getAccelerationStructureOpaqueCaptureDescriptorDataEXT => c.PFN_vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT,
                .cmdSetFragmentShadingRateEnumNV => c.PFN_vkCmdSetFragmentShadingRateEnumNV,
                .getDeviceFaultInfoEXT => c.PFN_vkGetDeviceFaultInfoEXT,
                .cmdSetVertexInputEXT => c.PFN_vkCmdSetVertexInputEXT,
                .getDeviceSubpassShadingMaxWorkgroupSizeHUAWEI => c.PFN_vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI,
                .cmdSubpassShadingHUAWEI => c.PFN_vkCmdSubpassShadingHUAWEI,
                .cmdBindInvocationMaskHUAWEI => c.PFN_vkCmdBindInvocationMaskHUAWEI,
                .getMemoryRemoteAddressNV => c.PFN_vkGetMemoryRemoteAddressNV,
                .getPipelinePropertiesEXT => c.PFN_vkGetPipelinePropertiesEXT,
                .cmdSetPatchControlPointsEXT => c.PFN_vkCmdSetPatchControlPointsEXT,
                .cmdSetRasterizerDiscardEnableEXT => c.PFN_vkCmdSetRasterizerDiscardEnableEXT,
                .cmdSetDepthBiasEnableEXT => c.PFN_vkCmdSetDepthBiasEnableEXT,
                .cmdSetLogicOpEXT => c.PFN_vkCmdSetLogicOpEXT,
                .cmdSetPrimitiveRestartEnableEXT => c.PFN_vkCmdSetPrimitiveRestartEnableEXT,
                .cmdSetColorWriteEnableEXT => c.PFN_vkCmdSetColorWriteEnableEXT,
                .cmdDrawMultiEXT => c.PFN_vkCmdDrawMultiEXT,
                .cmdDrawMultiIndexedEXT => c.PFN_vkCmdDrawMultiIndexedEXT,
                .createMicromapEXT => c.PFN_vkCreateMicromapEXT,
                .destroyMicromapEXT => c.PFN_vkDestroyMicromapEXT,
                .cmdBuildMicromapsEXT => c.PFN_vkCmdBuildMicromapsEXT,
                .buildMicromapsEXT => c.PFN_vkBuildMicromapsEXT,
                .copyMicromapEXT => c.PFN_vkCopyMicromapEXT,
                .copyMicromapToMemoryEXT => c.PFN_vkCopyMicromapToMemoryEXT,
                .copyMemoryToMicromapEXT => c.PFN_vkCopyMemoryToMicromapEXT,
                .writeMicromapsPropertiesEXT => c.PFN_vkWriteMicromapsPropertiesEXT,
                .cmdCopyMicromapEXT => c.PFN_vkCmdCopyMicromapEXT,
                .cmdCopyMicromapToMemoryEXT => c.PFN_vkCmdCopyMicromapToMemoryEXT,
                .cmdCopyMemoryToMicromapEXT => c.PFN_vkCmdCopyMemoryToMicromapEXT,
                .cmdWriteMicromapsPropertiesEXT => c.PFN_vkCmdWriteMicromapsPropertiesEXT,
                .getDeviceMicromapCompatibilityEXT => c.PFN_vkGetDeviceMicromapCompatibilityEXT,
                .getMicromapBuildSizesEXT => c.PFN_vkGetMicromapBuildSizesEXT,
                .cmdDrawClusterHUAWEI => c.PFN_vkCmdDrawClusterHUAWEI,
                .cmdDrawClusterIndirectHUAWEI => c.PFN_vkCmdDrawClusterIndirectHUAWEI,
                .setDeviceMemoryPriorityEXT => c.PFN_vkSetDeviceMemoryPriorityEXT,
                .getDescriptorSetLayoutHostMappingInfoVALVE => c.PFN_vkGetDescriptorSetLayoutHostMappingInfoVALVE,
                .getDescriptorSetHostMappingVALVE => c.PFN_vkGetDescriptorSetHostMappingVALVE,
                .cmdCopyMemoryIndirectNV => c.PFN_vkCmdCopyMemoryIndirectNV,
                .cmdCopyMemoryToImageIndirectNV => c.PFN_vkCmdCopyMemoryToImageIndirectNV,
                .cmdDecompressMemoryNV => c.PFN_vkCmdDecompressMemoryNV,
                .cmdDecompressMemoryIndirectCountNV => c.PFN_vkCmdDecompressMemoryIndirectCountNV,
                .getPipelineIndirectMemoryRequirementsNV => c.PFN_vkGetPipelineIndirectMemoryRequirementsNV,
                .cmdUpdatePipelineIndirectBufferNV => c.PFN_vkCmdUpdatePipelineIndirectBufferNV,
                .getPipelineIndirectDeviceAddressNV => c.PFN_vkGetPipelineIndirectDeviceAddressNV,
                .cmdSetDepthClampEnableEXT => c.PFN_vkCmdSetDepthClampEnableEXT,
                .cmdSetPolygonModeEXT => c.PFN_vkCmdSetPolygonModeEXT,
                .cmdSetRasterizationSamplesEXT => c.PFN_vkCmdSetRasterizationSamplesEXT,
                .cmdSetSampleMaskEXT => c.PFN_vkCmdSetSampleMaskEXT,
                .cmdSetAlphaToCoverageEnableEXT => c.PFN_vkCmdSetAlphaToCoverageEnableEXT,
                .cmdSetAlphaToOneEnableEXT => c.PFN_vkCmdSetAlphaToOneEnableEXT,
                .cmdSetLogicOpEnableEXT => c.PFN_vkCmdSetLogicOpEnableEXT,
                .cmdSetColorBlendEnableEXT => c.PFN_vkCmdSetColorBlendEnableEXT,
                .cmdSetColorBlendEquationEXT => c.PFN_vkCmdSetColorBlendEquationEXT,
                .cmdSetColorWriteMaskEXT => c.PFN_vkCmdSetColorWriteMaskEXT,
                .cmdSetTessellationDomainOriginEXT => c.PFN_vkCmdSetTessellationDomainOriginEXT,
                .cmdSetRasterizationStreamEXT => c.PFN_vkCmdSetRasterizationStreamEXT,
                .cmdSetConservativeRasterizationModeEXT => c.PFN_vkCmdSetConservativeRasterizationModeEXT,
                .cmdSetExtraPrimitiveOverestimationSizeEXT => c.PFN_vkCmdSetExtraPrimitiveOverestimationSizeEXT,
                .cmdSetDepthClipEnableEXT => c.PFN_vkCmdSetDepthClipEnableEXT,
                .cmdSetSampleLocationsEnableEXT => c.PFN_vkCmdSetSampleLocationsEnableEXT,
                .cmdSetColorBlendAdvancedEXT => c.PFN_vkCmdSetColorBlendAdvancedEXT,
                .cmdSetProvokingVertexModeEXT => c.PFN_vkCmdSetProvokingVertexModeEXT,
                .cmdSetLineRasterizationModeEXT => c.PFN_vkCmdSetLineRasterizationModeEXT,
                .cmdSetLineStippleEnableEXT => c.PFN_vkCmdSetLineStippleEnableEXT,
                .cmdSetDepthClipNegativeOneToOneEXT => c.PFN_vkCmdSetDepthClipNegativeOneToOneEXT,
                .cmdSetViewportWScalingEnableNV => c.PFN_vkCmdSetViewportWScalingEnableNV,
                .cmdSetViewportSwizzleNV => c.PFN_vkCmdSetViewportSwizzleNV,
                .cmdSetCoverageToColorEnableNV => c.PFN_vkCmdSetCoverageToColorEnableNV,
                .cmdSetCoverageToColorLocationNV => c.PFN_vkCmdSetCoverageToColorLocationNV,
                .cmdSetCoverageModulationModeNV => c.PFN_vkCmdSetCoverageModulationModeNV,
                .cmdSetCoverageModulationTableEnableNV => c.PFN_vkCmdSetCoverageModulationTableEnableNV,
                .cmdSetCoverageModulationTableNV => c.PFN_vkCmdSetCoverageModulationTableNV,
                .cmdSetShadingRateImageEnableNV => c.PFN_vkCmdSetShadingRateImageEnableNV,
                .cmdSetRepresentativeFragmentTestEnableNV => c.PFN_vkCmdSetRepresentativeFragmentTestEnableNV,
                .cmdSetCoverageReductionModeNV => c.PFN_vkCmdSetCoverageReductionModeNV,
                .getInstanceProcAddrLUNARG => c.PFN_vkGetInstanceProcAddrLUNARG,
                .getShaderModuleIdentifierEXT => c.PFN_vkGetShaderModuleIdentifierEXT,
                .getShaderModuleCreateInfoIdentifierEXT => c.PFN_vkGetShaderModuleCreateInfoIdentifierEXT,
                .getPhysicalDeviceOpticalFlowImageFormatsNV => c.PFN_vkGetPhysicalDeviceOpticalFlowImageFormatsNV,
                .createOpticalFlowSessionNV => c.PFN_vkCreateOpticalFlowSessionNV,
                .destroyOpticalFlowSessionNV => c.PFN_vkDestroyOpticalFlowSessionNV,
                .bindOpticalFlowSessionImageNV => c.PFN_vkBindOpticalFlowSessionImageNV,
                .cmdOpticalFlowExecuteNV => c.PFN_vkCmdOpticalFlowExecuteNV,
                .createShadersEXT => c.PFN_vkCreateShadersEXT,
                .destroyShaderEXT => c.PFN_vkDestroyShaderEXT,
                .getShaderBinaryDataEXT => c.PFN_vkGetShaderBinaryDataEXT,
                .cmdBindShadersEXT => c.PFN_vkCmdBindShadersEXT,
                .getFramebufferTilePropertiesQCOM => c.PFN_vkGetFramebufferTilePropertiesQCOM,
                .getDynamicRenderingTilePropertiesQCOM => c.PFN_vkGetDynamicRenderingTilePropertiesQCOM,
                .setLatencySleepModeNV => c.PFN_vkSetLatencySleepModeNV,
                .latencySleepNV => c.PFN_vkLatencySleepNV,
                .setLatencyMarkerNV => c.PFN_vkSetLatencyMarkerNV,
                .getLatencyTimingsNV => c.PFN_vkGetLatencyTimingsNV,
                .queueNotifyOutOfBandNV => c.PFN_vkQueueNotifyOutOfBandNV,
                .cmdSetAttachmentFeedbackLoopEnableEXT => c.PFN_vkCmdSetAttachmentFeedbackLoopEnableEXT,
                .createAccelerationStructureKHR => c.PFN_vkCreateAccelerationStructureKHR,
                .destroyAccelerationStructureKHR => c.PFN_vkDestroyAccelerationStructureKHR,
                .cmdBuildAccelerationStructuresKHR => c.PFN_vkCmdBuildAccelerationStructuresKHR,
                .cmdBuildAccelerationStructuresIndirectKHR => c.PFN_vkCmdBuildAccelerationStructuresIndirectKHR,
                .buildAccelerationStructuresKHR => c.PFN_vkBuildAccelerationStructuresKHR,
                .copyAccelerationStructureKHR => c.PFN_vkCopyAccelerationStructureKHR,
                .copyAccelerationStructureToMemoryKHR => c.PFN_vkCopyAccelerationStructureToMemoryKHR,
                .copyMemoryToAccelerationStructureKHR => c.PFN_vkCopyMemoryToAccelerationStructureKHR,
                .writeAccelerationStructuresPropertiesKHR => c.PFN_vkWriteAccelerationStructuresPropertiesKHR,
                .cmdCopyAccelerationStructureKHR => c.PFN_vkCmdCopyAccelerationStructureKHR,
                .cmdCopyAccelerationStructureToMemoryKHR => c.PFN_vkCmdCopyAccelerationStructureToMemoryKHR,
                .cmdCopyMemoryToAccelerationStructureKHR => c.PFN_vkCmdCopyMemoryToAccelerationStructureKHR,
                .getAccelerationStructureDeviceAddressKHR => c.PFN_vkGetAccelerationStructureDeviceAddressKHR,
                .cmdWriteAccelerationStructuresPropertiesKHR => c.PFN_vkCmdWriteAccelerationStructuresPropertiesKHR,
                .getDeviceAccelerationStructureCompatibilityKHR => c.PFN_vkGetDeviceAccelerationStructureCompatibilityKHR,
                .getAccelerationStructureBuildSizesKHR => c.PFN_vkGetAccelerationStructureBuildSizesKHR,
                .cmdTraceRaysKHR => c.PFN_vkCmdTraceRaysKHR,
                .createRayTracingPipelinesKHR => c.PFN_vkCreateRayTracingPipelinesKHR,
                .getRayTracingCaptureReplayShaderGroupHandlesKHR => c.PFN_vkGetRayTracingCaptureReplayShaderGroupHandlesKHR,
                .cmdTraceRaysIndirectKHR => c.PFN_vkCmdTraceRaysIndirectKHR,
                .getRayTracingShaderGroupStackSizeKHR => c.PFN_vkGetRayTracingShaderGroupStackSizeKHR,
                .cmdSetRayTracingPipelineStackSizeKHR => c.PFN_vkCmdSetRayTracingPipelineStackSizeKHR,
                .cmdDrawMeshTasksEXT => c.PFN_vkCmdDrawMeshTasksEXT,
                .cmdDrawMeshTasksIndirectEXT => c.PFN_vkCmdDrawMeshTasksIndirectEXT,
                .cmdDrawMeshTasksIndirectCountEXT => c.PFN_vkCmdDrawMeshTasksIndirectCountEXT,
            };
            pub const Inner: type = switch (@typeInfo(PFN)) {
                .optional => |optional| optional.child,
                else => |T| T,
            };

            pub fn load(instance: anytype) !Inner {
                const ptr = c.vkGetInstanceProcAddr(instance.toC(), name) orelse @panic("failed to find proc " ++ @tagName(func));
                return @ptrCast(ptr);
            }
        };
    }
};

pub fn imageMemBarrier(
    cmd_buf: c.VkCommandBuffer,
    image: c.VkImage,
    format: c.VkFormat,
    OldLayout: c.VkImageLayout,
    NewLayout: c.VkImageLayout,
) !void {
    var barrier: c.VkImageMemoryBarrier = .{
        .sType = c.VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
        .pNext = null,
        .srcAccessMask = 0,
        .dstAccessMask = 0,
        .oldLayout = OldLayout,
        .newLayout = NewLayout,
        .srcQueueFamilyIndex = c.VK_QUEUE_FAMILY_IGNORED,
        .dstQueueFamilyIndex = c.VK_QUEUE_FAMILY_IGNORED,
        .image = image,
        .subresourceRange = c.VkImageSubresourceRange{
            .aspectMask = c.VK_IMAGE_ASPECT_COLOR_BIT,
            .baseMipLevel = 0,
            .levelCount = 1,
            .baseArrayLayer = 0,
            .layerCount = 1,
        },
    };

    var sourceStage: c.VkPipelineStageFlags = c.VK_PIPELINE_STAGE_NONE;
    var destinationStage: c.VkPipelineStageFlags = c.VK_PIPELINE_STAGE_NONE;

    if (NewLayout == c.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL or
        (format == c.VK_FORMAT_D16_UNORM) or
        (format == c.VK_FORMAT_X8_D24_UNORM_PACK32) or
        (format == c.VK_FORMAT_D32_SFLOAT) or
        (format == c.VK_FORMAT_S8_UINT) or
        (format == c.VK_FORMAT_D16_UNORM_S8_UINT) or
        (format == c.VK_FORMAT_D24_UNORM_S8_UINT))
    {
        barrier.subresourceRange.aspectMask = c.VK_IMAGE_ASPECT_DEPTH_BIT;

        // if (HasStencilComponent(Format)) {
        //     barrier.subresourceRange.aspectMask |= c.VK_IMAGE_ASPECT_STENCIL_BIT;
        // }
    } else {
        barrier.subresourceRange.aspectMask = c.VK_IMAGE_ASPECT_COLOR_BIT;
    }

    if (OldLayout == c.VK_IMAGE_LAYOUT_UNDEFINED and NewLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL) {
        barrier.srcAccessMask = 0;
        barrier.dstAccessMask = c.VK_ACCESS_SHADER_READ_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    } else if (OldLayout == c.VK_IMAGE_LAYOUT_UNDEFINED and NewLayout == c.VK_IMAGE_LAYOUT_GENERAL) {
        barrier.srcAccessMask = 0;
        barrier.dstAccessMask = c.VK_ACCESS_SHADER_READ_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_TRANSFER_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    }

    if (OldLayout == c.VK_IMAGE_LAYOUT_UNDEFINED and
        NewLayout == c.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL)
    {
        barrier.srcAccessMask = 0;
        barrier.dstAccessMask = c.VK_ACCESS_TRANSFER_WRITE_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_TRANSFER_BIT;
    } // Convert back from read-only to updateable */
    else if (OldLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL) {
        barrier.srcAccessMask = c.VK_ACCESS_SHADER_READ_BIT;
        barrier.dstAccessMask = c.VK_ACCESS_TRANSFER_WRITE_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_TRANSFER_BIT;
    } //* Convert from updateable texture to shader read-only */
    else if (OldLayout == c.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL and
        NewLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL)
    {
        barrier.srcAccessMask = c.VK_ACCESS_TRANSFER_WRITE_BIT;
        barrier.dstAccessMask = c.VK_ACCESS_SHADER_READ_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_TRANSFER_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    } //* Convert depth texture from undefined state to depth-stencil buffer */
    else if (OldLayout == c.VK_IMAGE_LAYOUT_UNDEFINED and NewLayout == c.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL) {
        barrier.srcAccessMask = 0;
        barrier.dstAccessMask = c.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | c.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
    } //* Wait for render pass to complete */
    else if (OldLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL) {
        barrier.srcAccessMask = 0; // c.VK_ACCESS_SHADER_READ_BIT;
        barrier.dstAccessMask = 0;
        sourceStage = c.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    } //* Convert back from read-only to color attachment */
    else if (OldLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL) {
        barrier.srcAccessMask = c.VK_ACCESS_SHADER_READ_BIT;
        barrier.dstAccessMask = c.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    } //* Convert from updateable texture to shader read-only */
    else if (OldLayout == c.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL) {
        barrier.srcAccessMask = c.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
        barrier.dstAccessMask = c.VK_ACCESS_SHADER_READ_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    } //* Convert back from read-only to depth attachment */
    else if (OldLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL) {
        barrier.srcAccessMask = c.VK_ACCESS_SHADER_READ_BIT;
        barrier.dstAccessMask = c.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;
    } //* Convert from updateable depth texture to shader read-only */
    else if (OldLayout == c.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL) {
        barrier.srcAccessMask = c.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
        barrier.dstAccessMask = c.VK_ACCESS_SHADER_READ_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    } else if (OldLayout == c.VK_IMAGE_LAYOUT_UNDEFINED and NewLayout == c.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL) {
        barrier.srcAccessMask = 0;
        barrier.dstAccessMask = c.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    } else if (OldLayout == c.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_PRESENT_SRC_KHR) {
        barrier.srcAccessMask = c.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
        barrier.dstAccessMask = 0;

        sourceStage = c.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
    } else if (OldLayout == c.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_PRESENT_SRC_KHR) {
        barrier.srcAccessMask = c.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
        barrier.dstAccessMask = c.VK_ACCESS_NONE;

        sourceStage = c.VK_PIPELINE_STAGE_TRANSFER_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
    } else if (OldLayout == c.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL and NewLayout == c.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL) {
        barrier.srcAccessMask = c.VK_ACCESS_TRANSFER_WRITE_BIT;
        barrier.dstAccessMask = c.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

        sourceStage = c.VK_PIPELINE_STAGE_TRANSFER_BIT;
        destinationStage = c.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    } else {
        @panic("\nunsupported layout transition!\n");
    }

    c.vkCmdPipelineBarrier(
        cmd_buf,
        sourceStage,
        destinationStage,
        0,
        0,
        null,
        0,
        null,
        1,
        &barrier,
    );
}
